/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 67
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 52
#define ALIAS_COUNT 2
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 10
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_text = 1,
  sym_escape = 2,
  anon_sym_AT_LBRACE = 3,
  anon_sym_RBRACE = 4,
  anon_sym_AT_LT = 5,
  anon_sym_AT = 6,
  anon_sym_LT = 7,
  anon_sym_PIPE = 8,
  anon_sym_AT_GT = 9,
  anon_sym_GT = 10,
  anon_sym_AT_PIPE = 11,
  anon_sym_PIPE2 = 12,
  anon_sym_AT_LBRACK = 13,
  sym_block_close = 14,
  aux_sym__label_token1 = 15,
  anon_sym_SEMI = 16,
  anon_sym_LPAREN = 17,
  anon_sym_COMMA = 18,
  anon_sym_RPAREN = 19,
  anon_sym_LPAREN2 = 20,
  sym_atom = 21,
  sym_symbol = 22,
  sym_number = 23,
  anon_sym_SQUOTE = 24,
  aux_sym_quoted_atom_token1 = 25,
  anon_sym_SQUOTE2 = 26,
  sym_escape_sequence = 27,
  sym_comment = 28,
  sym_document = 29,
  sym_point = 30,
  sym_region_open = 31,
  sym_region_close = 32,
  sym_region_split = 33,
  sym_block_open = 34,
  sym__label = 35,
  sym__facts = 36,
  sym__expression = 37,
  sym_operator_expression = 38,
  sym__prefix_operator = 39,
  sym__infix_operator = 40,
  sym__primary = 41,
  sym__symbol_operand = 42,
  sym_compound = 43,
  sym_group = 44,
  sym_quoted_atom = 45,
  aux_sym_document_repeat1 = 46,
  aux_sym__facts_repeat1 = 47,
  aux_sym_operator_expression_repeat1 = 48,
  aux_sym_operator_expression_repeat2 = 49,
  aux_sym_compound_repeat1 = 50,
  aux_sym_quoted_atom_repeat1 = 51,
  alias_sym_functor = 52,
  alias_sym_operator = 53,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_text] = "text",
  [sym_escape] = "escape",
  [anon_sym_AT_LBRACE] = "@{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_AT_LT] = "@<",
  [anon_sym_AT] = "@",
  [anon_sym_LT] = "<",
  [anon_sym_PIPE] = "|",
  [anon_sym_AT_GT] = "@>",
  [anon_sym_GT] = ">",
  [anon_sym_AT_PIPE] = "@|",
  [anon_sym_PIPE2] = "|",
  [anon_sym_AT_LBRACK] = "@[",
  [sym_block_close] = "block_close",
  [aux_sym__label_token1] = "label",
  [anon_sym_SEMI] = ";",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LPAREN2] = "(",
  [sym_atom] = "atom",
  [sym_symbol] = "symbol",
  [sym_number] = "number",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_quoted_atom_token1] = "quoted_atom_token1",
  [anon_sym_SQUOTE2] = "'",
  [sym_escape_sequence] = "escape_sequence",
  [sym_comment] = "comment",
  [sym_document] = "document",
  [sym_point] = "point",
  [sym_region_open] = "region_open",
  [sym_region_close] = "region_close",
  [sym_region_split] = "region_split",
  [sym_block_open] = "block_open",
  [sym__label] = "_label",
  [sym__facts] = "_facts",
  [sym__expression] = "_expression",
  [sym_operator_expression] = "operator_expression",
  [sym__prefix_operator] = "_prefix_operator",
  [sym__infix_operator] = "_infix_operator",
  [sym__primary] = "_primary",
  [sym__symbol_operand] = "_symbol_operand",
  [sym_compound] = "compound",
  [sym_group] = "group",
  [sym_quoted_atom] = "quoted_atom",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym__facts_repeat1] = "_facts_repeat1",
  [aux_sym_operator_expression_repeat1] = "operator_expression_repeat1",
  [aux_sym_operator_expression_repeat2] = "operator_expression_repeat2",
  [aux_sym_compound_repeat1] = "compound_repeat1",
  [aux_sym_quoted_atom_repeat1] = "quoted_atom_repeat1",
  [alias_sym_functor] = "functor",
  [alias_sym_operator] = "operator",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_text] = sym_text,
  [sym_escape] = sym_escape,
  [anon_sym_AT_LBRACE] = anon_sym_AT_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_AT_LT] = anon_sym_AT_LT,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_AT_GT] = anon_sym_AT_GT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_AT_PIPE] = anon_sym_AT_PIPE,
  [anon_sym_PIPE2] = anon_sym_PIPE,
  [anon_sym_AT_LBRACK] = anon_sym_AT_LBRACK,
  [sym_block_close] = sym_block_close,
  [aux_sym__label_token1] = aux_sym__label_token1,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LPAREN2] = anon_sym_LPAREN,
  [sym_atom] = sym_atom,
  [sym_symbol] = sym_symbol,
  [sym_number] = sym_number,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_quoted_atom_token1] = aux_sym_quoted_atom_token1,
  [anon_sym_SQUOTE2] = anon_sym_SQUOTE,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_comment] = sym_comment,
  [sym_document] = sym_document,
  [sym_point] = sym_point,
  [sym_region_open] = sym_region_open,
  [sym_region_close] = sym_region_close,
  [sym_region_split] = sym_region_split,
  [sym_block_open] = sym_block_open,
  [sym__label] = sym__label,
  [sym__facts] = sym__facts,
  [sym__expression] = sym__expression,
  [sym_operator_expression] = sym_operator_expression,
  [sym__prefix_operator] = sym__prefix_operator,
  [sym__infix_operator] = sym__infix_operator,
  [sym__primary] = sym__primary,
  [sym__symbol_operand] = sym__symbol_operand,
  [sym_compound] = sym_compound,
  [sym_group] = sym_group,
  [sym_quoted_atom] = sym_quoted_atom,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym__facts_repeat1] = aux_sym__facts_repeat1,
  [aux_sym_operator_expression_repeat1] = aux_sym_operator_expression_repeat1,
  [aux_sym_operator_expression_repeat2] = aux_sym_operator_expression_repeat2,
  [aux_sym_compound_repeat1] = aux_sym_compound_repeat1,
  [aux_sym_quoted_atom_repeat1] = aux_sym_quoted_atom_repeat1,
  [alias_sym_functor] = alias_sym_functor,
  [alias_sym_operator] = alias_sym_operator,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_escape] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AT_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_block_close] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__label_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN2] = {
    .visible = true,
    .named = false,
  },
  [sym_atom] = {
    .visible = true,
    .named = true,
  },
  [sym_symbol] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_atom_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE2] = {
    .visible = true,
    .named = false,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_point] = {
    .visible = true,
    .named = true,
  },
  [sym_region_open] = {
    .visible = true,
    .named = true,
  },
  [sym_region_close] = {
    .visible = true,
    .named = true,
  },
  [sym_region_split] = {
    .visible = true,
    .named = true,
  },
  [sym_block_open] = {
    .visible = true,
    .named = true,
  },
  [sym__label] = {
    .visible = false,
    .named = true,
  },
  [sym__facts] = {
    .visible = false,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_operator_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__prefix_operator] = {
    .visible = false,
    .named = true,
  },
  [sym__infix_operator] = {
    .visible = false,
    .named = true,
  },
  [sym__primary] = {
    .visible = false,
    .named = true,
  },
  [sym__symbol_operand] = {
    .visible = false,
    .named = true,
  },
  [sym_compound] = {
    .visible = true,
    .named = true,
  },
  [sym_group] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_atom] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__facts_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_operator_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_operator_expression_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_compound_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quoted_atom_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_functor] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_operator] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_argument = 1,
  field_functor = 2,
  field_label = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_argument] = "argument",
  [field_functor] = "functor",
  [field_label] = "label",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [2] = {.index = 0, .length = 1},
  [3] = {.index = 1, .length = 1},
  [4] = {.index = 2, .length = 2},
  [5] = {.index = 2, .length = 2},
  [6] = {.index = 4, .length = 1},
  [7] = {.index = 5, .length = 3},
  [8] = {.index = 8, .length = 2},
  [9] = {.index = 5, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_label, 0},
  [1] =
    {field_label, 1, .inherited = true},
  [2] =
    {field_argument, 2},
    {field_functor, 0},
  [4] =
    {field_argument, 1},
  [5] =
    {field_argument, 2},
    {field_argument, 3, .inherited = true},
    {field_functor, 0},
  [8] =
    {field_argument, 0, .inherited = true},
    {field_argument, 1, .inherited = true},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = alias_sym_operator,
  },
  [4] = {
    [0] = alias_sym_functor,
  },
  [7] = {
    [0] = alias_sym_functor,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
};

static const TSCharacterRange sym_symbol_character_set_1[] = {
  {'&', '&'}, {'*', '+'}, {'-', '/'}, {':', ':'}, {'<', '>'}, {'@', '@'}, {'\\', '\\'}, {'^', '^'},
  {'~', '~'},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(31);
      ADVANCE_MAP(
        '\'', 75,
        '(', 54,
        ')', 56,
        ',', 55,
        '-', 16,
        '/', 7,
        ';', 53,
        '<', 42,
        '>', 45,
        '@', 41,
        '|', 47,
        '}', 39,
        '#', 52,
        '$', 52,
        '?', 52,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(29);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(66);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 1:
      if (lookahead == ' ') ADVANCE(70);
      if (lookahead == '\'') ADVANCE(76);
      if (lookahead == '/') ADVANCE(73);
      if (lookahead == '\\') ADVANCE(14);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(13);
      if (lookahead > ' ' &&
          lookahead != 0x7f &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(74);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '\'', 69,
        '(', 54,
        ')', 56,
        ',', 55,
        '-', 64,
        '/', 61,
        ';', 53,
        '|', 43,
        '}', 39,
        '#', 60,
        '$', 60,
        '?', 60,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(66);
      if (('&' <= lookahead && lookahead <= '@') ||
          lookahead == '\\' ||
          lookahead == '^' ||
          lookahead == '~') ADVANCE(65);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '\'', 69,
        '(', 57,
        ')', 56,
        ',', 55,
        '-', 64,
        '/', 61,
        ';', 53,
        '|', 43,
        '}', 39,
        '#', 60,
        '$', 60,
        '?', 60,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(66);
      if (('&' <= lookahead && lookahead <= '@') ||
          lookahead == '\\' ||
          lookahead == '^' ||
          lookahead == '~') ADVANCE(65);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 4:
      if (lookahead == '\'') ADVANCE(69);
      if (lookahead == '(') ADVANCE(57);
      if (lookahead == '-') ADVANCE(64);
      if (lookahead == '/') ADVANCE(61);
      if (lookahead == '#' ||
          lookahead == '$' ||
          lookahead == '?') ADVANCE(60);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(66);
      if (lookahead == '&' ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('.' <= lookahead && lookahead <= ':') ||
          ('<' <= lookahead && lookahead <= '@') ||
          lookahead == '\\' ||
          lookahead == '^' ||
          lookahead == '~') ADVANCE(65);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 5:
      ADVANCE_MAP(
        '(', 54,
        ')', 56,
        ',', 55,
        '/', 61,
        ';', 53,
        '|', 43,
        '}', 39,
        '#', 60,
        '$', 60,
        '?', 60,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (lookahead == '&' ||
          ('*' <= lookahead && lookahead <= '.') ||
          (':' <= lookahead && lookahead <= '@') ||
          lookahead == '\\' ||
          lookahead == '^' ||
          lookahead == '~') ADVANCE(65);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 6:
      ADVANCE_MAP(
        ')', 56,
        ',', 55,
        '/', 61,
        ';', 53,
        '|', 43,
        '}', 39,
        '#', 60,
        '$', 60,
        '?', 60,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (lookahead == '&' ||
          ('*' <= lookahead && lookahead <= '.') ||
          (':' <= lookahead && lookahead <= '@') ||
          lookahead == '\\' ||
          lookahead == '^' ||
          lookahead == '~') ADVANCE(65);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 7:
      if (lookahead == '*') ADVANCE(9);
      END_STATE();
    case 8:
      if (lookahead == '*') ADVANCE(8);
      if (lookahead == '/') ADVANCE(78);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(9);
      END_STATE();
    case 9:
      if (lookahead == '*') ADVANCE(8);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == '/') ADVANCE(7);
      if (lookahead == ';') ADVANCE(53);
      if (lookahead == '|') ADVANCE(43);
      if (lookahead == '}') ADVANCE(39);
      if (lookahead == '#' ||
          lookahead == '$' ||
          lookahead == '?') ADVANCE(52);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(11);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 11:
      if (lookahead == '/') ADVANCE(7);
      if (lookahead == ';') ADVANCE(53);
      if (lookahead == '|') ADVANCE(43);
      if (lookahead == '}') ADVANCE(39);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(11);
      END_STATE();
    case 12:
      if (lookahead == '/') ADVANCE(7);
      if (lookahead == '<') ADVANCE(42);
      if (lookahead == '>') ADVANCE(45);
      if (lookahead == '|') ADVANCE(47);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(13);
      END_STATE();
    case 13:
      if (lookahead == '/') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(13);
      END_STATE();
    case 14:
      if (lookahead == 'U') ADVANCE(26);
      if (lookahead == 'u') ADVANCE(22);
      if (lookahead == '\'' ||
          lookahead == '\\' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't') ADVANCE(77);
      END_STATE();
    case 15:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(68);
      END_STATE();
    case 16:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(66);
      END_STATE();
    case 17:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(67);
      END_STATE();
    case 18:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(68);
      END_STATE();
    case 19:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(77);
      END_STATE();
    case 20:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(19);
      END_STATE();
    case 21:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(20);
      END_STATE();
    case 22:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(21);
      END_STATE();
    case 23:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(22);
      END_STATE();
    case 24:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(23);
      END_STATE();
    case 25:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(24);
      END_STATE();
    case 26:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(25);
      END_STATE();
    case 27:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 28:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 29:
      if (eof) ADVANCE(31);
      ADVANCE_MAP(
        '\'', 69,
        '(', 57,
        ')', 56,
        ',', 55,
        '-', 16,
        '/', 7,
        ';', 53,
        '@', 41,
        '|', 43,
        '}', 39,
        '#', 60,
        '$', 60,
        '?', 60,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(29);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(66);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 30:
      if (eof) ADVANCE(31);
      if (lookahead == '/') ADVANCE(34);
      if (lookahead == '@') ADVANCE(41);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(36);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '*') ADVANCE(32);
      if (lookahead == '/') ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != '@' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(33);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '*') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '@' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '*') ADVANCE(33);
      if (lookahead != 0 &&
          lookahead != '@' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(36);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '/') ADVANCE(34);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '@' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(36);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '@' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_escape);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_AT_LBRACE);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_AT_LT);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_AT);
      if (lookahead == '<') ADVANCE(40);
      if (lookahead == '>') ADVANCE(44);
      if (lookahead == '@') ADVANCE(37);
      if (lookahead == '[') ADVANCE(48);
      if (lookahead == ']') ADVANCE(49);
      if (lookahead == '{') ADVANCE(38);
      if (lookahead == '|') ADVANCE(46);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_AT_GT);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_AT_PIPE);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_PIPE2);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_AT_LBRACK);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_block_close);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym__label_token1);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym__label_token1);
      if (lookahead == '_') ADVANCE(27);
      if (lookahead == '#' ||
          lookahead == '$' ||
          lookahead == '?') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym__label_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_LPAREN2);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_atom);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == '_') ADVANCE(28);
      if (lookahead == '#' ||
          lookahead == '$' ||
          lookahead == '?') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_atom);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == '*') ADVANCE(63);
      if (set_contains(sym_symbol_character_set_1, 9, lookahead)) ADVANCE(65);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == '*') ADVANCE(62);
      if (lookahead == '/') ADVANCE(65);
      if (set_contains(sym_symbol_character_set_1, 9, lookahead)) ADVANCE(63);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(9);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == '*') ADVANCE(62);
      if (set_contains(sym_symbol_character_set_1, 9, lookahead)) ADVANCE(63);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(9);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_symbol);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(66);
      if (set_contains(sym_symbol_character_set_1, 9, lookahead)) ADVANCE(65);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_symbol);
      if (set_contains(sym_symbol_character_set_1, 9, lookahead)) ADVANCE(65);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(17);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(66);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(67);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(68);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(aux_sym_quoted_atom_token1);
      if (lookahead == ' ') ADVANCE(70);
      if (lookahead == '/') ADVANCE(73);
      if (lookahead > ' ' &&
          lookahead != '\'' &&
          lookahead != '\\' &&
          lookahead != 0x7f &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(74);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(aux_sym_quoted_atom_token1);
      if (lookahead == '*') ADVANCE(71);
      if (lookahead == '/') ADVANCE(74);
      if (lookahead > 0x1f &&
          lookahead != '\'' &&
          lookahead != '\\' &&
          lookahead != 0x7f &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(72);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(aux_sym_quoted_atom_token1);
      if (lookahead == '*') ADVANCE(71);
      if (lookahead > 0x1f &&
          lookahead != '\'' &&
          lookahead != '\\' &&
          lookahead != 0x7f &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(72);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(aux_sym_quoted_atom_token1);
      if (lookahead == '*') ADVANCE(72);
      if (lookahead > 0x1f &&
          lookahead != '\'' &&
          lookahead != '\\' &&
          lookahead != 0x7f &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(74);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(aux_sym_quoted_atom_token1);
      if (lookahead > 0x1f &&
          lookahead != '\'' &&
          lookahead != '\\' &&
          lookahead != 0x7f &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(74);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_SQUOTE2);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_SQUOTE2);
      if (lookahead == '\'') ADVANCE(77);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 30},
  [2] = {.lex_state = 30},
  [3] = {.lex_state = 30},
  [4] = {.lex_state = 4},
  [5] = {.lex_state = 4},
  [6] = {.lex_state = 4},
  [7] = {.lex_state = 4},
  [8] = {.lex_state = 4},
  [9] = {.lex_state = 4},
  [10] = {.lex_state = 4},
  [11] = {.lex_state = 4},
  [12] = {.lex_state = 4},
  [13] = {.lex_state = 4},
  [14] = {.lex_state = 4},
  [15] = {.lex_state = 4},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 30},
  [19] = {.lex_state = 30},
  [20] = {.lex_state = 30},
  [21] = {.lex_state = 30},
  [22] = {.lex_state = 30},
  [23] = {.lex_state = 30},
  [24] = {.lex_state = 30},
  [25] = {.lex_state = 30},
  [26] = {.lex_state = 5},
  [27] = {.lex_state = 5},
  [28] = {.lex_state = 5},
  [29] = {.lex_state = 5},
  [30] = {.lex_state = 5},
  [31] = {.lex_state = 5},
  [32] = {.lex_state = 5},
  [33] = {.lex_state = 5},
  [34] = {.lex_state = 5},
  [35] = {.lex_state = 4},
  [36] = {.lex_state = 5},
  [37] = {.lex_state = 5},
  [38] = {.lex_state = 5},
  [39] = {.lex_state = 5},
  [40] = {.lex_state = 5},
  [41] = {.lex_state = 5},
  [42] = {.lex_state = 4},
  [43] = {.lex_state = 4},
  [44] = {.lex_state = 4},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 10},
  [47] = {.lex_state = 10},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 10},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 10},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 12},
  [54] = {.lex_state = 12},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 10},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 10},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 10},
  [65] = {.lex_state = 10},
  [66] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_escape] = ACTIONS(1),
    [anon_sym_AT_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_AT_LT] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_AT_GT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_AT_PIPE] = ACTIONS(1),
    [anon_sym_PIPE2] = ACTIONS(1),
    [anon_sym_AT_LBRACK] = ACTIONS(1),
    [sym_block_close] = ACTIONS(1),
    [aux_sym__label_token1] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LPAREN2] = ACTIONS(1),
    [sym_atom] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE2] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_document] = STATE(66),
    [sym_point] = STATE(2),
    [sym_region_open] = STATE(2),
    [sym_region_close] = STATE(2),
    [sym_region_split] = STATE(2),
    [sym_block_open] = STATE(2),
    [aux_sym_document_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_text] = ACTIONS(7),
    [sym_escape] = ACTIONS(9),
    [anon_sym_AT_LBRACE] = ACTIONS(11),
    [anon_sym_AT_LT] = ACTIONS(13),
    [anon_sym_AT] = ACTIONS(15),
    [anon_sym_AT_GT] = ACTIONS(17),
    [anon_sym_AT_PIPE] = ACTIONS(19),
    [anon_sym_AT_LBRACK] = ACTIONS(21),
    [sym_block_close] = ACTIONS(9),
    [sym_comment] = ACTIONS(23),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(11), 1,
      anon_sym_AT_LBRACE,
    ACTIONS(13), 1,
      anon_sym_AT_LT,
    ACTIONS(15), 1,
      anon_sym_AT,
    ACTIONS(17), 1,
      anon_sym_AT_GT,
    ACTIONS(19), 1,
      anon_sym_AT_PIPE,
    ACTIONS(21), 1,
      anon_sym_AT_LBRACK,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
    ACTIONS(27), 1,
      sym_text,
    ACTIONS(29), 2,
      sym_escape,
      sym_block_close,
    STATE(3), 6,
      sym_point,
      sym_region_open,
      sym_region_close,
      sym_region_split,
      sym_block_open,
      aux_sym_document_repeat1,
  [40] = 11,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(31), 1,
      ts_builtin_sym_end,
    ACTIONS(33), 1,
      sym_text,
    ACTIONS(39), 1,
      anon_sym_AT_LBRACE,
    ACTIONS(42), 1,
      anon_sym_AT_LT,
    ACTIONS(45), 1,
      anon_sym_AT,
    ACTIONS(48), 1,
      anon_sym_AT_GT,
    ACTIONS(51), 1,
      anon_sym_AT_PIPE,
    ACTIONS(54), 1,
      anon_sym_AT_LBRACK,
    ACTIONS(36), 2,
      sym_escape,
      sym_block_close,
    STATE(3), 6,
      sym_point,
      sym_region_open,
      sym_region_close,
      sym_region_split,
      sym_block_open,
      aux_sym_document_repeat1,
  [80] = 11,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(57), 1,
      anon_sym_LPAREN2,
    ACTIONS(59), 1,
      sym_atom,
    ACTIONS(61), 1,
      sym_symbol,
    ACTIONS(63), 1,
      sym_number,
    ACTIONS(65), 1,
      anon_sym_SQUOTE,
    STATE(32), 1,
      sym_quoted_atom,
    STATE(61), 1,
      sym__facts,
    STATE(13), 2,
      sym__prefix_operator,
      aux_sym_operator_expression_repeat1,
    STATE(49), 2,
      sym__expression,
      sym_operator_expression,
    STATE(27), 4,
      sym__primary,
      sym__symbol_operand,
      sym_compound,
      sym_group,
  [119] = 11,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(57), 1,
      anon_sym_LPAREN2,
    ACTIONS(59), 1,
      sym_atom,
    ACTIONS(61), 1,
      sym_symbol,
    ACTIONS(63), 1,
      sym_number,
    ACTIONS(65), 1,
      anon_sym_SQUOTE,
    STATE(32), 1,
      sym_quoted_atom,
    STATE(65), 1,
      sym__facts,
    STATE(13), 2,
      sym__prefix_operator,
      aux_sym_operator_expression_repeat1,
    STATE(49), 2,
      sym__expression,
      sym_operator_expression,
    STATE(27), 4,
      sym__primary,
      sym__symbol_operand,
      sym_compound,
      sym_group,
  [158] = 11,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(57), 1,
      anon_sym_LPAREN2,
    ACTIONS(59), 1,
      sym_atom,
    ACTIONS(61), 1,
      sym_symbol,
    ACTIONS(63), 1,
      sym_number,
    ACTIONS(65), 1,
      anon_sym_SQUOTE,
    STATE(32), 1,
      sym_quoted_atom,
    STATE(62), 1,
      sym__facts,
    STATE(13), 2,
      sym__prefix_operator,
      aux_sym_operator_expression_repeat1,
    STATE(49), 2,
      sym__expression,
      sym_operator_expression,
    STATE(27), 4,
      sym__primary,
      sym__symbol_operand,
      sym_compound,
      sym_group,
  [197] = 11,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(57), 1,
      anon_sym_LPAREN2,
    ACTIONS(59), 1,
      sym_atom,
    ACTIONS(61), 1,
      sym_symbol,
    ACTIONS(63), 1,
      sym_number,
    ACTIONS(65), 1,
      anon_sym_SQUOTE,
    STATE(32), 1,
      sym_quoted_atom,
    STATE(64), 1,
      sym__facts,
    STATE(13), 2,
      sym__prefix_operator,
      aux_sym_operator_expression_repeat1,
    STATE(49), 2,
      sym__expression,
      sym_operator_expression,
    STATE(27), 4,
      sym__primary,
      sym__symbol_operand,
      sym_compound,
      sym_group,
  [236] = 10,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(57), 1,
      anon_sym_LPAREN2,
    ACTIONS(59), 1,
      sym_atom,
    ACTIONS(61), 1,
      sym_symbol,
    ACTIONS(63), 1,
      sym_number,
    ACTIONS(65), 1,
      anon_sym_SQUOTE,
    STATE(32), 1,
      sym_quoted_atom,
    STATE(13), 2,
      sym__prefix_operator,
      aux_sym_operator_expression_repeat1,
    STATE(63), 2,
      sym__expression,
      sym_operator_expression,
    STATE(27), 4,
      sym__primary,
      sym__symbol_operand,
      sym_compound,
      sym_group,
  [272] = 10,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(57), 1,
      anon_sym_LPAREN2,
    ACTIONS(59), 1,
      sym_atom,
    ACTIONS(61), 1,
      sym_symbol,
    ACTIONS(63), 1,
      sym_number,
    ACTIONS(65), 1,
      anon_sym_SQUOTE,
    STATE(32), 1,
      sym_quoted_atom,
    STATE(13), 2,
      sym__prefix_operator,
      aux_sym_operator_expression_repeat1,
    STATE(56), 2,
      sym__expression,
      sym_operator_expression,
    STATE(27), 4,
      sym__primary,
      sym__symbol_operand,
      sym_compound,
      sym_group,
  [308] = 10,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(57), 1,
      anon_sym_LPAREN2,
    ACTIONS(59), 1,
      sym_atom,
    ACTIONS(61), 1,
      sym_symbol,
    ACTIONS(63), 1,
      sym_number,
    ACTIONS(65), 1,
      anon_sym_SQUOTE,
    STATE(32), 1,
      sym_quoted_atom,
    STATE(13), 2,
      sym__prefix_operator,
      aux_sym_operator_expression_repeat1,
    STATE(52), 2,
      sym__expression,
      sym_operator_expression,
    STATE(27), 4,
      sym__primary,
      sym__symbol_operand,
      sym_compound,
      sym_group,
  [344] = 10,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(57), 1,
      anon_sym_LPAREN2,
    ACTIONS(59), 1,
      sym_atom,
    ACTIONS(61), 1,
      sym_symbol,
    ACTIONS(63), 1,
      sym_number,
    ACTIONS(65), 1,
      anon_sym_SQUOTE,
    STATE(32), 1,
      sym_quoted_atom,
    STATE(13), 2,
      sym__prefix_operator,
      aux_sym_operator_expression_repeat1,
    STATE(51), 2,
      sym__expression,
      sym_operator_expression,
    STATE(27), 4,
      sym__primary,
      sym__symbol_operand,
      sym_compound,
      sym_group,
  [380] = 10,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(57), 1,
      anon_sym_LPAREN2,
    ACTIONS(59), 1,
      sym_atom,
    ACTIONS(61), 1,
      sym_symbol,
    ACTIONS(63), 1,
      sym_number,
    ACTIONS(65), 1,
      anon_sym_SQUOTE,
    STATE(32), 1,
      sym_quoted_atom,
    STATE(13), 2,
      sym__prefix_operator,
      aux_sym_operator_expression_repeat1,
    STATE(59), 2,
      sym__expression,
      sym_operator_expression,
    STATE(27), 4,
      sym__primary,
      sym__symbol_operand,
      sym_compound,
      sym_group,
  [416] = 9,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(57), 1,
      anon_sym_LPAREN2,
    ACTIONS(59), 1,
      sym_atom,
    ACTIONS(61), 1,
      sym_symbol,
    ACTIONS(65), 1,
      anon_sym_SQUOTE,
    ACTIONS(67), 1,
      sym_number,
    STATE(32), 1,
      sym_quoted_atom,
    STATE(35), 2,
      sym__prefix_operator,
      aux_sym_operator_expression_repeat1,
    STATE(26), 4,
      sym__primary,
      sym__symbol_operand,
      sym_compound,
      sym_group,
  [448] = 9,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(57), 1,
      anon_sym_LPAREN2,
    ACTIONS(59), 1,
      sym_atom,
    ACTIONS(61), 1,
      sym_symbol,
    ACTIONS(65), 1,
      anon_sym_SQUOTE,
    ACTIONS(69), 1,
      sym_number,
    STATE(32), 1,
      sym_quoted_atom,
    STATE(15), 2,
      sym__prefix_operator,
      aux_sym_operator_expression_repeat1,
    STATE(41), 4,
      sym__primary,
      sym__symbol_operand,
      sym_compound,
      sym_group,
  [480] = 9,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(57), 1,
      anon_sym_LPAREN2,
    ACTIONS(59), 1,
      sym_atom,
    ACTIONS(61), 1,
      sym_symbol,
    ACTIONS(65), 1,
      anon_sym_SQUOTE,
    ACTIONS(71), 1,
      sym_number,
    STATE(32), 1,
      sym_quoted_atom,
    STATE(35), 2,
      sym__prefix_operator,
      aux_sym_operator_expression_repeat1,
    STATE(39), 4,
      sym__primary,
      sym__symbol_operand,
      sym_compound,
      sym_group,
  [512] = 7,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(75), 1,
      anon_sym_LPAREN,
    ACTIONS(77), 1,
      anon_sym_LPAREN2,
    ACTIONS(79), 1,
      sym_atom,
    ACTIONS(82), 1,
      sym_symbol,
    ACTIONS(85), 2,
      sym_number,
      anon_sym_SQUOTE,
    ACTIONS(73), 5,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [539] = 7,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(75), 1,
      anon_sym_LPAREN,
    ACTIONS(77), 1,
      anon_sym_LPAREN2,
    ACTIONS(89), 1,
      sym_atom,
    ACTIONS(92), 1,
      sym_symbol,
    ACTIONS(85), 2,
      sym_number,
      anon_sym_SQUOTE,
    ACTIONS(87), 5,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [566] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(95), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(97), 8,
      sym_escape,
      anon_sym_AT_LBRACE,
      anon_sym_AT_LT,
      anon_sym_AT,
      anon_sym_AT_GT,
      anon_sym_AT_PIPE,
      anon_sym_AT_LBRACK,
      sym_block_close,
  [584] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(99), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(101), 8,
      sym_escape,
      anon_sym_AT_LBRACE,
      anon_sym_AT_LT,
      anon_sym_AT,
      anon_sym_AT_GT,
      anon_sym_AT_PIPE,
      anon_sym_AT_LBRACK,
      sym_block_close,
  [602] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(103), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(105), 8,
      sym_escape,
      anon_sym_AT_LBRACE,
      anon_sym_AT_LT,
      anon_sym_AT,
      anon_sym_AT_GT,
      anon_sym_AT_PIPE,
      anon_sym_AT_LBRACK,
      sym_block_close,
  [620] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(107), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(109), 8,
      sym_escape,
      anon_sym_AT_LBRACE,
      anon_sym_AT_LT,
      anon_sym_AT,
      anon_sym_AT_GT,
      anon_sym_AT_PIPE,
      anon_sym_AT_LBRACK,
      sym_block_close,
  [638] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(111), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(113), 8,
      sym_escape,
      anon_sym_AT_LBRACE,
      anon_sym_AT_LT,
      anon_sym_AT,
      anon_sym_AT_GT,
      anon_sym_AT_PIPE,
      anon_sym_AT_LBRACK,
      sym_block_close,
  [656] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(115), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(117), 8,
      sym_escape,
      anon_sym_AT_LBRACE,
      anon_sym_AT_LT,
      anon_sym_AT,
      anon_sym_AT_GT,
      anon_sym_AT_PIPE,
      anon_sym_AT_LBRACK,
      sym_block_close,
  [674] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(119), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(121), 8,
      sym_escape,
      anon_sym_AT_LBRACE,
      anon_sym_AT_LT,
      anon_sym_AT,
      anon_sym_AT_GT,
      anon_sym_AT_PIPE,
      anon_sym_AT_LBRACK,
      sym_block_close,
  [692] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(123), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(125), 8,
      sym_escape,
      anon_sym_AT_LBRACE,
      anon_sym_AT_LT,
      anon_sym_AT,
      anon_sym_AT_GT,
      anon_sym_AT_PIPE,
      anon_sym_AT_LBRACK,
      sym_block_close,
  [710] = 6,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(129), 1,
      sym_atom,
    ACTIONS(131), 1,
      sym_symbol,
    STATE(14), 1,
      sym__infix_operator,
    STATE(29), 1,
      aux_sym_operator_expression_repeat2,
    ACTIONS(127), 5,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [733] = 6,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(129), 1,
      sym_atom,
    ACTIONS(131), 1,
      sym_symbol,
    STATE(14), 1,
      sym__infix_operator,
    STATE(28), 1,
      aux_sym_operator_expression_repeat2,
    ACTIONS(133), 5,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [756] = 6,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(129), 1,
      sym_atom,
    ACTIONS(131), 1,
      sym_symbol,
    STATE(14), 1,
      sym__infix_operator,
    STATE(30), 1,
      aux_sym_operator_expression_repeat2,
    ACTIONS(127), 5,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [779] = 6,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(129), 1,
      sym_atom,
    ACTIONS(131), 1,
      sym_symbol,
    STATE(14), 1,
      sym__infix_operator,
    STATE(30), 1,
      aux_sym_operator_expression_repeat2,
    ACTIONS(135), 5,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [802] = 6,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(139), 1,
      sym_atom,
    ACTIONS(142), 1,
      sym_symbol,
    STATE(14), 1,
      sym__infix_operator,
    STATE(30), 1,
      aux_sym_operator_expression_repeat2,
    ACTIONS(137), 5,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [825] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(147), 1,
      sym_symbol,
    ACTIONS(145), 7,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_atom,
  [841] = 4,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(149), 1,
      anon_sym_LPAREN,
    ACTIONS(151), 1,
      sym_symbol,
    ACTIONS(73), 6,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_atom,
  [859] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(155), 1,
      sym_symbol,
    ACTIONS(153), 7,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_atom,
  [875] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(159), 1,
      sym_symbol,
    ACTIONS(157), 6,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_atom,
  [890] = 5,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(163), 1,
      sym_atom,
    ACTIONS(166), 1,
      sym_symbol,
    STATE(35), 2,
      sym__prefix_operator,
      aux_sym_operator_expression_repeat1,
    ACTIONS(161), 3,
      anon_sym_LPAREN2,
      sym_number,
      anon_sym_SQUOTE,
  [909] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(171), 1,
      sym_symbol,
    ACTIONS(169), 6,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_atom,
  [924] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(175), 1,
      sym_symbol,
    ACTIONS(173), 6,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_atom,
  [939] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(179), 1,
      sym_symbol,
    ACTIONS(177), 6,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_atom,
  [954] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(183), 1,
      sym_symbol,
    ACTIONS(181), 6,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_atom,
  [969] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(187), 1,
      sym_symbol,
    ACTIONS(185), 6,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_atom,
  [984] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(189), 1,
      sym_symbol,
    ACTIONS(137), 6,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_atom,
  [999] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(193), 1,
      sym_symbol,
    ACTIONS(191), 4,
      anon_sym_LPAREN2,
      sym_atom,
      sym_number,
      anon_sym_SQUOTE,
  [1012] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(197), 1,
      sym_symbol,
    ACTIONS(195), 4,
      anon_sym_LPAREN2,
      sym_atom,
      sym_number,
      anon_sym_SQUOTE,
  [1025] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(77), 1,
      sym_symbol,
    ACTIONS(85), 4,
      anon_sym_LPAREN2,
      sym_atom,
      sym_number,
      anon_sym_SQUOTE,
  [1038] = 4,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(201), 1,
      anon_sym_SQUOTE2,
    STATE(50), 1,
      aux_sym_quoted_atom_repeat1,
    ACTIONS(199), 2,
      aux_sym_quoted_atom_token1,
      sym_escape_sequence,
  [1052] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 1,
      anon_sym_SEMI,
    STATE(47), 1,
      aux_sym__facts_repeat1,
    ACTIONS(203), 2,
      anon_sym_RBRACE,
      anon_sym_PIPE,
  [1066] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(209), 1,
      anon_sym_SEMI,
    STATE(47), 1,
      aux_sym__facts_repeat1,
    ACTIONS(207), 2,
      anon_sym_RBRACE,
      anon_sym_PIPE,
  [1080] = 4,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(214), 1,
      anon_sym_SQUOTE2,
    STATE(45), 1,
      aux_sym_quoted_atom_repeat1,
    ACTIONS(212), 2,
      aux_sym_quoted_atom_token1,
      sym_escape_sequence,
  [1094] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 1,
      anon_sym_SEMI,
    STATE(46), 1,
      aux_sym__facts_repeat1,
    ACTIONS(216), 2,
      anon_sym_RBRACE,
      anon_sym_PIPE,
  [1108] = 4,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(221), 1,
      anon_sym_SQUOTE2,
    STATE(50), 1,
      aux_sym_quoted_atom_repeat1,
    ACTIONS(218), 2,
      aux_sym_quoted_atom_token1,
      sym_escape_sequence,
  [1122] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(207), 3,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_SEMI,
  [1131] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 1,
      anon_sym_COMMA,
    ACTIONS(225), 1,
      anon_sym_RPAREN,
    STATE(57), 1,
      aux_sym_compound_repeat1,
  [1144] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 1,
      anon_sym_LT,
    ACTIONS(229), 1,
      anon_sym_GT,
    ACTIONS(231), 1,
      anon_sym_PIPE2,
  [1157] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(233), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_PIPE2,
  [1166] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 1,
      anon_sym_COMMA,
    ACTIONS(235), 1,
      anon_sym_RPAREN,
    STATE(58), 1,
      aux_sym_compound_repeat1,
  [1179] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 1,
      anon_sym_COMMA,
    ACTIONS(237), 1,
      anon_sym_RPAREN,
    STATE(55), 1,
      aux_sym_compound_repeat1,
  [1192] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 1,
      anon_sym_COMMA,
    ACTIONS(239), 1,
      anon_sym_RPAREN,
    STATE(58), 1,
      aux_sym_compound_repeat1,
  [1205] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(241), 1,
      anon_sym_COMMA,
    ACTIONS(244), 1,
      anon_sym_RPAREN,
    STATE(58), 1,
      aux_sym_compound_repeat1,
  [1218] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(246), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1226] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(248), 1,
      aux_sym__label_token1,
    STATE(53), 1,
      sym__label,
  [1236] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(250), 1,
      anon_sym_RBRACE,
  [1243] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(252), 1,
      anon_sym_PIPE,
  [1250] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 1,
      anon_sym_RPAREN,
  [1257] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(256), 1,
      anon_sym_PIPE,
  [1264] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 1,
      anon_sym_PIPE,
  [1271] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(260), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 40,
  [SMALL_STATE(4)] = 80,
  [SMALL_STATE(5)] = 119,
  [SMALL_STATE(6)] = 158,
  [SMALL_STATE(7)] = 197,
  [SMALL_STATE(8)] = 236,
  [SMALL_STATE(9)] = 272,
  [SMALL_STATE(10)] = 308,
  [SMALL_STATE(11)] = 344,
  [SMALL_STATE(12)] = 380,
  [SMALL_STATE(13)] = 416,
  [SMALL_STATE(14)] = 448,
  [SMALL_STATE(15)] = 480,
  [SMALL_STATE(16)] = 512,
  [SMALL_STATE(17)] = 539,
  [SMALL_STATE(18)] = 566,
  [SMALL_STATE(19)] = 584,
  [SMALL_STATE(20)] = 602,
  [SMALL_STATE(21)] = 620,
  [SMALL_STATE(22)] = 638,
  [SMALL_STATE(23)] = 656,
  [SMALL_STATE(24)] = 674,
  [SMALL_STATE(25)] = 692,
  [SMALL_STATE(26)] = 710,
  [SMALL_STATE(27)] = 733,
  [SMALL_STATE(28)] = 756,
  [SMALL_STATE(29)] = 779,
  [SMALL_STATE(30)] = 802,
  [SMALL_STATE(31)] = 825,
  [SMALL_STATE(32)] = 841,
  [SMALL_STATE(33)] = 859,
  [SMALL_STATE(34)] = 875,
  [SMALL_STATE(35)] = 890,
  [SMALL_STATE(36)] = 909,
  [SMALL_STATE(37)] = 924,
  [SMALL_STATE(38)] = 939,
  [SMALL_STATE(39)] = 954,
  [SMALL_STATE(40)] = 969,
  [SMALL_STATE(41)] = 984,
  [SMALL_STATE(42)] = 999,
  [SMALL_STATE(43)] = 1012,
  [SMALL_STATE(44)] = 1025,
  [SMALL_STATE(45)] = 1038,
  [SMALL_STATE(46)] = 1052,
  [SMALL_STATE(47)] = 1066,
  [SMALL_STATE(48)] = 1080,
  [SMALL_STATE(49)] = 1094,
  [SMALL_STATE(50)] = 1108,
  [SMALL_STATE(51)] = 1122,
  [SMALL_STATE(52)] = 1131,
  [SMALL_STATE(53)] = 1144,
  [SMALL_STATE(54)] = 1157,
  [SMALL_STATE(55)] = 1166,
  [SMALL_STATE(56)] = 1179,
  [SMALL_STATE(57)] = 1192,
  [SMALL_STATE(58)] = 1205,
  [SMALL_STATE(59)] = 1218,
  [SMALL_STATE(60)] = 1226,
  [SMALL_STATE(61)] = 1236,
  [SMALL_STATE(62)] = 1243,
  [SMALL_STATE(63)] = 1250,
  [SMALL_STATE(64)] = 1257,
  [SMALL_STATE(65)] = 1264,
  [SMALL_STATE(66)] = 1271,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [51] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [54] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__primary, 1, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__prefix_operator, 1, 0, 1),
  [79] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym__prefix_operator, 1, 0, 1), REDUCE(sym__primary, 1, 0, 0),
  [82] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym__prefix_operator, 1, 0, 1), REDUCE(sym__primary, 1, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__prefix_operator, 1, 0, 1),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__symbol_operand, 1, -1, 0),
  [89] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym__prefix_operator, 1, 0, 1), REDUCE(sym__symbol_operand, 1, -1, 0),
  [92] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym__prefix_operator, 1, 0, 1), REDUCE(sym__symbol_operand, 1, -1, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_region_close, 1, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_region_close, 1, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_region_split, 1, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_region_split, 1, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_point, 3, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_point, 3, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_region_close, 3, 0, 3),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_region_close, 3, 0, 3),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_open, 3, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_open, 3, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_region_split, 3, 0, 3),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_region_split, 3, 0, 3),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_region_open, 3, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_region_open, 3, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_region_open, 5, 0, 3),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_region_open, 5, 0, 3),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operator_expression, 2, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [131] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operator_expression, 3, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_operator_expression_repeat2, 2, 0, 0),
  [139] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_operator_expression_repeat2, 2, 0, 0), SHIFT_REPEAT(43),
  [142] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_operator_expression_repeat2, 2, 0, 0), SHIFT_REPEAT(42),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_atom, 3, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_atom, 3, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__primary, 1, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_atom, 2, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_atom, 2, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group, 3, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_group, 3, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_operator_expression_repeat1, 2, 0, 0),
  [163] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_operator_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [166] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_operator_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compound, 5, 0, 9),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_compound, 5, 0, 9),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compound, 5, 0, 7),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_compound, 5, 0, 7),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compound, 4, 0, 4),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_compound, 4, 0, 4),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_operator_expression_repeat2, 3, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_operator_expression_repeat2, 3, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compound, 4, 0, 5),
  [187] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_compound, 4, 0, 5),
  [189] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_operator_expression_repeat2, 2, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__infix_operator, 1, 2, 1),
  [193] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__infix_operator, 1, 2, 1),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__infix_operator, 1, 1, 1),
  [197] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__infix_operator, 1, 1, 1),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [201] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__facts, 2, 0, 0),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__facts_repeat1, 2, 0, 0),
  [209] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__facts_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [214] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__facts, 1, 0, 0),
  [218] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quoted_atom_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [221] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quoted_atom_repeat1, 2, 0, 0),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__label, 1, 0, 2),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [241] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_compound_repeat1, 2, 0, 8), SHIFT_REPEAT(12),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_compound_repeat1, 2, 0, 8),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_compound_repeat1, 2, 0, 6),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [260] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_ilk(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "ilk",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
