/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 76
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 56
#define ALIAS_COUNT 2
#define TOKEN_COUNT 31
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 13
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_text = 1,
  sym_escape = 2,
  anon_sym_AT_LBRACE = 3,
  anon_sym_RBRACE = 4,
  anon_sym_AT_LT = 5,
  anon_sym_AT = 6,
  anon_sym_LT = 7,
  anon_sym_PIPE = 8,
  anon_sym_AT_GT = 9,
  anon_sym_GT = 10,
  anon_sym_AT_PIPE = 11,
  anon_sym_PIPE2 = 12,
  anon_sym_AT_LBRACK = 13,
  sym_block_close = 14,
  aux_sym__label_token1 = 15,
  anon_sym_SEMI = 16,
  anon_sym_LPAREN = 17,
  anon_sym_COMMA = 18,
  anon_sym_RPAREN = 19,
  anon_sym_LBRACK = 20,
  anon_sym_RBRACK = 21,
  anon_sym_LPAREN2 = 22,
  sym_atom = 23,
  sym_symbol = 24,
  sym_number = 25,
  anon_sym_SQUOTE = 26,
  aux_sym_quoted_atom_token1 = 27,
  anon_sym_SQUOTE2 = 28,
  sym_escape_sequence = 29,
  sym_comment = 30,
  sym_document = 31,
  sym_point = 32,
  sym_region_open = 33,
  sym_region_close = 34,
  sym_region_split = 35,
  sym_block_open = 36,
  sym__label = 37,
  sym__facts = 38,
  sym__expression = 39,
  sym_operator_expression = 40,
  sym__prefix_operator = 41,
  sym__infix_operator = 42,
  sym__primary = 43,
  sym__symbol_operand = 44,
  sym_compound = 45,
  sym_sequence = 46,
  sym_group = 47,
  sym_quoted_atom = 48,
  aux_sym_document_repeat1 = 49,
  aux_sym__facts_repeat1 = 50,
  aux_sym_operator_expression_repeat1 = 51,
  aux_sym_operator_expression_repeat2 = 52,
  aux_sym_compound_repeat1 = 53,
  aux_sym_sequence_repeat1 = 54,
  aux_sym_quoted_atom_repeat1 = 55,
  alias_sym_functor = 56,
  alias_sym_operator = 57,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_text] = "text",
  [sym_escape] = "escape",
  [anon_sym_AT_LBRACE] = "@{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_AT_LT] = "@<",
  [anon_sym_AT] = "@",
  [anon_sym_LT] = "<",
  [anon_sym_PIPE] = "|",
  [anon_sym_AT_GT] = "@>",
  [anon_sym_GT] = ">",
  [anon_sym_AT_PIPE] = "@|",
  [anon_sym_PIPE2] = "|",
  [anon_sym_AT_LBRACK] = "@[",
  [sym_block_close] = "block_close",
  [aux_sym__label_token1] = "label",
  [anon_sym_SEMI] = ";",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LPAREN2] = "(",
  [sym_atom] = "atom",
  [sym_symbol] = "symbol",
  [sym_number] = "number",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_quoted_atom_token1] = "quoted_atom_token1",
  [anon_sym_SQUOTE2] = "'",
  [sym_escape_sequence] = "escape_sequence",
  [sym_comment] = "comment",
  [sym_document] = "document",
  [sym_point] = "point",
  [sym_region_open] = "region_open",
  [sym_region_close] = "region_close",
  [sym_region_split] = "region_split",
  [sym_block_open] = "block_open",
  [sym__label] = "_label",
  [sym__facts] = "_facts",
  [sym__expression] = "_expression",
  [sym_operator_expression] = "operator_expression",
  [sym__prefix_operator] = "_prefix_operator",
  [sym__infix_operator] = "_infix_operator",
  [sym__primary] = "_primary",
  [sym__symbol_operand] = "_symbol_operand",
  [sym_compound] = "compound",
  [sym_sequence] = "sequence",
  [sym_group] = "group",
  [sym_quoted_atom] = "quoted_atom",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym__facts_repeat1] = "_facts_repeat1",
  [aux_sym_operator_expression_repeat1] = "operator_expression_repeat1",
  [aux_sym_operator_expression_repeat2] = "operator_expression_repeat2",
  [aux_sym_compound_repeat1] = "compound_repeat1",
  [aux_sym_sequence_repeat1] = "sequence_repeat1",
  [aux_sym_quoted_atom_repeat1] = "quoted_atom_repeat1",
  [alias_sym_functor] = "functor",
  [alias_sym_operator] = "operator",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_text] = sym_text,
  [sym_escape] = sym_escape,
  [anon_sym_AT_LBRACE] = anon_sym_AT_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_AT_LT] = anon_sym_AT_LT,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_AT_GT] = anon_sym_AT_GT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_AT_PIPE] = anon_sym_AT_PIPE,
  [anon_sym_PIPE2] = anon_sym_PIPE,
  [anon_sym_AT_LBRACK] = anon_sym_AT_LBRACK,
  [sym_block_close] = sym_block_close,
  [aux_sym__label_token1] = aux_sym__label_token1,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LPAREN2] = anon_sym_LPAREN,
  [sym_atom] = sym_atom,
  [sym_symbol] = sym_symbol,
  [sym_number] = sym_number,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_quoted_atom_token1] = aux_sym_quoted_atom_token1,
  [anon_sym_SQUOTE2] = anon_sym_SQUOTE,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_comment] = sym_comment,
  [sym_document] = sym_document,
  [sym_point] = sym_point,
  [sym_region_open] = sym_region_open,
  [sym_region_close] = sym_region_close,
  [sym_region_split] = sym_region_split,
  [sym_block_open] = sym_block_open,
  [sym__label] = sym__label,
  [sym__facts] = sym__facts,
  [sym__expression] = sym__expression,
  [sym_operator_expression] = sym_operator_expression,
  [sym__prefix_operator] = sym__prefix_operator,
  [sym__infix_operator] = sym__infix_operator,
  [sym__primary] = sym__primary,
  [sym__symbol_operand] = sym__symbol_operand,
  [sym_compound] = sym_compound,
  [sym_sequence] = sym_sequence,
  [sym_group] = sym_group,
  [sym_quoted_atom] = sym_quoted_atom,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym__facts_repeat1] = aux_sym__facts_repeat1,
  [aux_sym_operator_expression_repeat1] = aux_sym_operator_expression_repeat1,
  [aux_sym_operator_expression_repeat2] = aux_sym_operator_expression_repeat2,
  [aux_sym_compound_repeat1] = aux_sym_compound_repeat1,
  [aux_sym_sequence_repeat1] = aux_sym_sequence_repeat1,
  [aux_sym_quoted_atom_repeat1] = aux_sym_quoted_atom_repeat1,
  [alias_sym_functor] = alias_sym_functor,
  [alias_sym_operator] = alias_sym_operator,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_escape] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AT_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_block_close] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__label_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN2] = {
    .visible = true,
    .named = false,
  },
  [sym_atom] = {
    .visible = true,
    .named = true,
  },
  [sym_symbol] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_atom_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE2] = {
    .visible = true,
    .named = false,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_point] = {
    .visible = true,
    .named = true,
  },
  [sym_region_open] = {
    .visible = true,
    .named = true,
  },
  [sym_region_close] = {
    .visible = true,
    .named = true,
  },
  [sym_region_split] = {
    .visible = true,
    .named = true,
  },
  [sym_block_open] = {
    .visible = true,
    .named = true,
  },
  [sym__label] = {
    .visible = false,
    .named = true,
  },
  [sym__facts] = {
    .visible = false,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_operator_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__prefix_operator] = {
    .visible = false,
    .named = true,
  },
  [sym__infix_operator] = {
    .visible = false,
    .named = true,
  },
  [sym__primary] = {
    .visible = false,
    .named = true,
  },
  [sym__symbol_operand] = {
    .visible = false,
    .named = true,
  },
  [sym_compound] = {
    .visible = true,
    .named = true,
  },
  [sym_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_group] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_atom] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__facts_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_operator_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_operator_expression_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_compound_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_sequence_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quoted_atom_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_functor] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_operator] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_argument = 1,
  field_element = 2,
  field_functor = 3,
  field_label = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_argument] = "argument",
  [field_element] = "element",
  [field_functor] = "functor",
  [field_label] = "label",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [2] = {.index = 0, .length = 1},
  [3] = {.index = 1, .length = 1},
  [4] = {.index = 2, .length = 1},
  [5] = {.index = 3, .length = 2},
  [6] = {.index = 5, .length = 2},
  [7] = {.index = 7, .length = 2},
  [8] = {.index = 7, .length = 2},
  [9] = {.index = 9, .length = 1},
  [10] = {.index = 10, .length = 3},
  [11] = {.index = 13, .length = 2},
  [12] = {.index = 10, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_label, 0},
  [1] =
    {field_label, 1, .inherited = true},
  [2] =
    {field_element, 1},
  [3] =
    {field_element, 1},
    {field_element, 2, .inherited = true},
  [5] =
    {field_element, 0, .inherited = true},
    {field_element, 1, .inherited = true},
  [7] =
    {field_argument, 2},
    {field_functor, 0},
  [9] =
    {field_argument, 1},
  [10] =
    {field_argument, 2},
    {field_argument, 3, .inherited = true},
    {field_functor, 0},
  [13] =
    {field_argument, 0, .inherited = true},
    {field_argument, 1, .inherited = true},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = alias_sym_operator,
  },
  [7] = {
    [0] = alias_sym_functor,
  },
  [10] = {
    [0] = alias_sym_functor,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
};

static const TSCharacterRange sym_symbol_character_set_1[] = {
  {'&', '&'}, {'*', '+'}, {'-', '/'}, {':', ':'}, {'<', '>'}, {'@', '@'}, {'\\', '\\'}, {'^', '^'},
  {'~', '~'},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(31);
      ADVANCE_MAP(
        '\'', 77,
        '(', 54,
        ')', 56,
        ',', 55,
        '-', 16,
        '/', 7,
        ';', 53,
        '<', 42,
        '>', 45,
        '@', 41,
        '[', 57,
        ']', 58,
        '|', 47,
        '}', 39,
        '#', 52,
        '$', 52,
        '?', 52,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(29);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(68);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 1:
      if (lookahead == ' ') ADVANCE(72);
      if (lookahead == '\'') ADVANCE(78);
      if (lookahead == '/') ADVANCE(75);
      if (lookahead == '\\') ADVANCE(14);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(13);
      if (lookahead > ' ' &&
          lookahead != 0x7f &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(76);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '\'', 71,
        '(', 54,
        ')', 56,
        ',', 55,
        '-', 66,
        '/', 63,
        ';', 53,
        '[', 57,
        ']', 58,
        '|', 43,
        '}', 39,
        '#', 62,
        '$', 62,
        '?', 62,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(68);
      if (('&' <= lookahead && lookahead <= '@') ||
          ('\\' <= lookahead && lookahead <= '^') ||
          lookahead == '~') ADVANCE(67);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '\'', 71,
        '(', 59,
        ')', 56,
        ',', 55,
        '-', 66,
        '/', 63,
        ';', 53,
        '[', 57,
        ']', 58,
        '|', 43,
        '}', 39,
        '#', 62,
        '$', 62,
        '?', 62,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(68);
      if (('&' <= lookahead && lookahead <= '@') ||
          ('\\' <= lookahead && lookahead <= '^') ||
          lookahead == '~') ADVANCE(67);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    case 4:
      ADVANCE_MAP(
        '\'', 71,
        '(', 59,
        '-', 66,
        '/', 63,
        '[', 57,
        ']', 58,
        '#', 62,
        '$', 62,
        '?', 62,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(68);
      if (lookahead == '&' ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('.' <= lookahead && lookahead <= ':') ||
          ('<' <= lookahead && lookahead <= '@') ||
          ('\\' <= lookahead && lookahead <= '^') ||
          lookahead == '~') ADVANCE(67);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    case 5:
      ADVANCE_MAP(
        '(', 54,
        ')', 56,
        ',', 55,
        '/', 63,
        ';', 53,
        ']', 58,
        '|', 43,
        '}', 39,
        '#', 62,
        '$', 62,
        '?', 62,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (lookahead == '&' ||
          ('*' <= lookahead && lookahead <= '.') ||
          (':' <= lookahead && lookahead <= '@') ||
          ('\\' <= lookahead && lookahead <= '^') ||
          lookahead == '~') ADVANCE(67);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    case 6:
      ADVANCE_MAP(
        ')', 56,
        ',', 55,
        '/', 63,
        ';', 53,
        ']', 58,
        '|', 43,
        '}', 39,
        '#', 62,
        '$', 62,
        '?', 62,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (lookahead == '&' ||
          ('*' <= lookahead && lookahead <= '.') ||
          (':' <= lookahead && lookahead <= '@') ||
          ('\\' <= lookahead && lookahead <= '^') ||
          lookahead == '~') ADVANCE(67);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    case 7:
      if (lookahead == '*') ADVANCE(9);
      END_STATE();
    case 8:
      if (lookahead == '*') ADVANCE(8);
      if (lookahead == '/') ADVANCE(80);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(9);
      END_STATE();
    case 9:
      if (lookahead == '*') ADVANCE(8);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == '/') ADVANCE(7);
      if (lookahead == ';') ADVANCE(53);
      if (lookahead == '|') ADVANCE(43);
      if (lookahead == '}') ADVANCE(39);
      if (lookahead == '#' ||
          lookahead == '$' ||
          lookahead == '?') ADVANCE(52);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(11);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 11:
      if (lookahead == '/') ADVANCE(7);
      if (lookahead == ';') ADVANCE(53);
      if (lookahead == '|') ADVANCE(43);
      if (lookahead == '}') ADVANCE(39);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(11);
      END_STATE();
    case 12:
      if (lookahead == '/') ADVANCE(7);
      if (lookahead == '<') ADVANCE(42);
      if (lookahead == '>') ADVANCE(45);
      if (lookahead == '|') ADVANCE(47);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(13);
      END_STATE();
    case 13:
      if (lookahead == '/') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(13);
      END_STATE();
    case 14:
      if (lookahead == 'U') ADVANCE(26);
      if (lookahead == 'u') ADVANCE(22);
      if (lookahead == '\'' ||
          lookahead == '\\' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't') ADVANCE(79);
      END_STATE();
    case 15:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(70);
      END_STATE();
    case 16:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(68);
      END_STATE();
    case 17:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(69);
      END_STATE();
    case 18:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(70);
      END_STATE();
    case 19:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(79);
      END_STATE();
    case 20:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(19);
      END_STATE();
    case 21:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(20);
      END_STATE();
    case 22:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(21);
      END_STATE();
    case 23:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(22);
      END_STATE();
    case 24:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(23);
      END_STATE();
    case 25:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(24);
      END_STATE();
    case 26:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(25);
      END_STATE();
    case 27:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 28:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    case 29:
      if (eof) ADVANCE(31);
      ADVANCE_MAP(
        '\'', 71,
        '(', 59,
        ')', 56,
        ',', 55,
        '-', 16,
        '/', 7,
        ';', 53,
        '@', 41,
        '[', 57,
        ']', 58,
        '|', 43,
        '}', 39,
        '#', 62,
        '$', 62,
        '?', 62,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(29);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(68);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    case 30:
      if (eof) ADVANCE(31);
      if (lookahead == '/') ADVANCE(34);
      if (lookahead == '@') ADVANCE(41);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(36);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '*') ADVANCE(32);
      if (lookahead == '/') ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != '@' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(33);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '*') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '@' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '*') ADVANCE(33);
      if (lookahead != 0 &&
          lookahead != '@' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(36);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '/') ADVANCE(34);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '@' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(36);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '@' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_escape);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_AT_LBRACE);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_AT_LT);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_AT);
      if (lookahead == '<') ADVANCE(40);
      if (lookahead == '>') ADVANCE(44);
      if (lookahead == '@') ADVANCE(37);
      if (lookahead == '[') ADVANCE(48);
      if (lookahead == ']') ADVANCE(49);
      if (lookahead == '{') ADVANCE(38);
      if (lookahead == '|') ADVANCE(46);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_AT_GT);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_AT_PIPE);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_PIPE2);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_AT_LBRACK);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_block_close);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym__label_token1);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym__label_token1);
      if (lookahead == '_') ADVANCE(27);
      if (lookahead == '#' ||
          lookahead == '$' ||
          lookahead == '?') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym__label_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_LPAREN2);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_atom);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == '_') ADVANCE(28);
      if (lookahead == '#' ||
          lookahead == '$' ||
          lookahead == '?') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_atom);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == '*') ADVANCE(65);
      if (set_contains(sym_symbol_character_set_1, 9, lookahead)) ADVANCE(67);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == '*') ADVANCE(64);
      if (lookahead == '/') ADVANCE(67);
      if (set_contains(sym_symbol_character_set_1, 9, lookahead)) ADVANCE(65);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(9);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == '*') ADVANCE(64);
      if (set_contains(sym_symbol_character_set_1, 9, lookahead)) ADVANCE(65);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(9);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_symbol);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(68);
      if (set_contains(sym_symbol_character_set_1, 9, lookahead)) ADVANCE(67);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_symbol);
      if (set_contains(sym_symbol_character_set_1, 9, lookahead)) ADVANCE(67);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(17);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(68);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(69);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(70);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(aux_sym_quoted_atom_token1);
      if (lookahead == ' ') ADVANCE(72);
      if (lookahead == '/') ADVANCE(75);
      if (lookahead > ' ' &&
          lookahead != '\'' &&
          lookahead != '\\' &&
          lookahead != 0x7f &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(76);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(aux_sym_quoted_atom_token1);
      if (lookahead == '*') ADVANCE(73);
      if (lookahead == '/') ADVANCE(76);
      if (lookahead > 0x1f &&
          lookahead != '\'' &&
          lookahead != '\\' &&
          lookahead != 0x7f &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(74);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(aux_sym_quoted_atom_token1);
      if (lookahead == '*') ADVANCE(73);
      if (lookahead > 0x1f &&
          lookahead != '\'' &&
          lookahead != '\\' &&
          lookahead != 0x7f &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(74);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(aux_sym_quoted_atom_token1);
      if (lookahead == '*') ADVANCE(74);
      if (lookahead > 0x1f &&
          lookahead != '\'' &&
          lookahead != '\\' &&
          lookahead != 0x7f &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(76);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(aux_sym_quoted_atom_token1);
      if (lookahead > 0x1f &&
          lookahead != '\'' &&
          lookahead != '\\' &&
          lookahead != 0x7f &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(76);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_SQUOTE2);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_SQUOTE2);
      if (lookahead == '\'') ADVANCE(79);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 30},
  [2] = {.lex_state = 4},
  [3] = {.lex_state = 4},
  [4] = {.lex_state = 4},
  [5] = {.lex_state = 4},
  [6] = {.lex_state = 4},
  [7] = {.lex_state = 30},
  [8] = {.lex_state = 4},
  [9] = {.lex_state = 30},
  [10] = {.lex_state = 4},
  [11] = {.lex_state = 4},
  [12] = {.lex_state = 4},
  [13] = {.lex_state = 4},
  [14] = {.lex_state = 4},
  [15] = {.lex_state = 4},
  [16] = {.lex_state = 4},
  [17] = {.lex_state = 4},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 30},
  [21] = {.lex_state = 30},
  [22] = {.lex_state = 30},
  [23] = {.lex_state = 30},
  [24] = {.lex_state = 30},
  [25] = {.lex_state = 5},
  [26] = {.lex_state = 5},
  [27] = {.lex_state = 30},
  [28] = {.lex_state = 5},
  [29] = {.lex_state = 30},
  [30] = {.lex_state = 30},
  [31] = {.lex_state = 5},
  [32] = {.lex_state = 5},
  [33] = {.lex_state = 5},
  [34] = {.lex_state = 5},
  [35] = {.lex_state = 5},
  [36] = {.lex_state = 5},
  [37] = {.lex_state = 5},
  [38] = {.lex_state = 4},
  [39] = {.lex_state = 5},
  [40] = {.lex_state = 5},
  [41] = {.lex_state = 5},
  [42] = {.lex_state = 5},
  [43] = {.lex_state = 5},
  [44] = {.lex_state = 5},
  [45] = {.lex_state = 5},
  [46] = {.lex_state = 5},
  [47] = {.lex_state = 4},
  [48] = {.lex_state = 4},
  [49] = {.lex_state = 4},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 10},
  [52] = {.lex_state = 10},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 10},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 12},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 12},
  [60] = {.lex_state = 10},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 10},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 10},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 10},
  [74] = {.lex_state = 10},
  [75] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_escape] = ACTIONS(1),
    [anon_sym_AT_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_AT_LT] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_AT_GT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_AT_PIPE] = ACTIONS(1),
    [anon_sym_PIPE2] = ACTIONS(1),
    [anon_sym_AT_LBRACK] = ACTIONS(1),
    [sym_block_close] = ACTIONS(1),
    [aux_sym__label_token1] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LPAREN2] = ACTIONS(1),
    [sym_atom] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE2] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_document] = STATE(75),
    [sym_point] = STATE(7),
    [sym_region_open] = STATE(7),
    [sym_region_close] = STATE(7),
    [sym_region_split] = STATE(7),
    [sym_block_open] = STATE(7),
    [aux_sym_document_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_text] = ACTIONS(7),
    [sym_escape] = ACTIONS(9),
    [anon_sym_AT_LBRACE] = ACTIONS(11),
    [anon_sym_AT_LT] = ACTIONS(13),
    [anon_sym_AT] = ACTIONS(15),
    [anon_sym_AT_GT] = ACTIONS(17),
    [anon_sym_AT_PIPE] = ACTIONS(19),
    [anon_sym_AT_LBRACK] = ACTIONS(21),
    [sym_block_close] = ACTIONS(9),
    [sym_comment] = ACTIONS(23),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_LPAREN2,
    ACTIONS(29), 1,
      sym_atom,
    ACTIONS(31), 1,
      sym_symbol,
    ACTIONS(33), 1,
      sym_number,
    ACTIONS(35), 1,
      anon_sym_SQUOTE,
    STATE(33), 1,
      sym_quoted_atom,
    STATE(72), 1,
      sym__facts,
    STATE(15), 2,
      sym__prefix_operator,
      aux_sym_operator_expression_repeat1,
    STATE(51), 2,
      sym__expression,
      sym_operator_expression,
    STATE(28), 5,
      sym__primary,
      sym__symbol_operand,
      sym_compound,
      sym_sequence,
      sym_group,
  [43] = 12,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_LPAREN2,
    ACTIONS(29), 1,
      sym_atom,
    ACTIONS(31), 1,
      sym_symbol,
    ACTIONS(33), 1,
      sym_number,
    ACTIONS(35), 1,
      anon_sym_SQUOTE,
    STATE(33), 1,
      sym_quoted_atom,
    STATE(73), 1,
      sym__facts,
    STATE(15), 2,
      sym__prefix_operator,
      aux_sym_operator_expression_repeat1,
    STATE(51), 2,
      sym__expression,
      sym_operator_expression,
    STATE(28), 5,
      sym__primary,
      sym__symbol_operand,
      sym_compound,
      sym_sequence,
      sym_group,
  [86] = 12,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_LPAREN2,
    ACTIONS(29), 1,
      sym_atom,
    ACTIONS(31), 1,
      sym_symbol,
    ACTIONS(33), 1,
      sym_number,
    ACTIONS(35), 1,
      anon_sym_SQUOTE,
    STATE(33), 1,
      sym_quoted_atom,
    STATE(74), 1,
      sym__facts,
    STATE(15), 2,
      sym__prefix_operator,
      aux_sym_operator_expression_repeat1,
    STATE(51), 2,
      sym__expression,
      sym_operator_expression,
    STATE(28), 5,
      sym__primary,
      sym__symbol_operand,
      sym_compound,
      sym_sequence,
      sym_group,
  [129] = 12,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_LPAREN2,
    ACTIONS(29), 1,
      sym_atom,
    ACTIONS(31), 1,
      sym_symbol,
    ACTIONS(33), 1,
      sym_number,
    ACTIONS(35), 1,
      anon_sym_SQUOTE,
    ACTIONS(37), 1,
      anon_sym_RBRACK,
    STATE(33), 1,
      sym_quoted_atom,
    STATE(15), 2,
      sym__prefix_operator,
      aux_sym_operator_expression_repeat1,
    STATE(62), 2,
      sym__expression,
      sym_operator_expression,
    STATE(28), 5,
      sym__primary,
      sym__symbol_operand,
      sym_compound,
      sym_sequence,
      sym_group,
  [172] = 12,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_LPAREN2,
    ACTIONS(29), 1,
      sym_atom,
    ACTIONS(31), 1,
      sym_symbol,
    ACTIONS(33), 1,
      sym_number,
    ACTIONS(35), 1,
      anon_sym_SQUOTE,
    STATE(33), 1,
      sym_quoted_atom,
    STATE(70), 1,
      sym__facts,
    STATE(15), 2,
      sym__prefix_operator,
      aux_sym_operator_expression_repeat1,
    STATE(51), 2,
      sym__expression,
      sym_operator_expression,
    STATE(28), 5,
      sym__primary,
      sym__symbol_operand,
      sym_compound,
      sym_sequence,
      sym_group,
  [215] = 11,
    ACTIONS(11), 1,
      anon_sym_AT_LBRACE,
    ACTIONS(13), 1,
      anon_sym_AT_LT,
    ACTIONS(15), 1,
      anon_sym_AT,
    ACTIONS(17), 1,
      anon_sym_AT_GT,
    ACTIONS(19), 1,
      anon_sym_AT_PIPE,
    ACTIONS(21), 1,
      anon_sym_AT_LBRACK,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
    ACTIONS(41), 1,
      sym_text,
    ACTIONS(43), 2,
      sym_escape,
      sym_block_close,
    STATE(9), 6,
      sym_point,
      sym_region_open,
      sym_region_close,
      sym_region_split,
      sym_block_open,
      aux_sym_document_repeat1,
  [255] = 11,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_LPAREN2,
    ACTIONS(29), 1,
      sym_atom,
    ACTIONS(31), 1,
      sym_symbol,
    ACTIONS(33), 1,
      sym_number,
    ACTIONS(35), 1,
      anon_sym_SQUOTE,
    STATE(33), 1,
      sym_quoted_atom,
    STATE(15), 2,
      sym__prefix_operator,
      aux_sym_operator_expression_repeat1,
    STATE(71), 2,
      sym__expression,
      sym_operator_expression,
    STATE(28), 5,
      sym__primary,
      sym__symbol_operand,
      sym_compound,
      sym_sequence,
      sym_group,
  [295] = 11,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(45), 1,
      ts_builtin_sym_end,
    ACTIONS(47), 1,
      sym_text,
    ACTIONS(53), 1,
      anon_sym_AT_LBRACE,
    ACTIONS(56), 1,
      anon_sym_AT_LT,
    ACTIONS(59), 1,
      anon_sym_AT,
    ACTIONS(62), 1,
      anon_sym_AT_GT,
    ACTIONS(65), 1,
      anon_sym_AT_PIPE,
    ACTIONS(68), 1,
      anon_sym_AT_LBRACK,
    ACTIONS(50), 2,
      sym_escape,
      sym_block_close,
    STATE(9), 6,
      sym_point,
      sym_region_open,
      sym_region_close,
      sym_region_split,
      sym_block_open,
      aux_sym_document_repeat1,
  [335] = 11,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_LPAREN2,
    ACTIONS(29), 1,
      sym_atom,
    ACTIONS(31), 1,
      sym_symbol,
    ACTIONS(33), 1,
      sym_number,
    ACTIONS(35), 1,
      anon_sym_SQUOTE,
    STATE(33), 1,
      sym_quoted_atom,
    STATE(15), 2,
      sym__prefix_operator,
      aux_sym_operator_expression_repeat1,
    STATE(60), 2,
      sym__expression,
      sym_operator_expression,
    STATE(28), 5,
      sym__primary,
      sym__symbol_operand,
      sym_compound,
      sym_sequence,
      sym_group,
  [375] = 11,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_LPAREN2,
    ACTIONS(29), 1,
      sym_atom,
    ACTIONS(31), 1,
      sym_symbol,
    ACTIONS(33), 1,
      sym_number,
    ACTIONS(35), 1,
      anon_sym_SQUOTE,
    STATE(33), 1,
      sym_quoted_atom,
    STATE(15), 2,
      sym__prefix_operator,
      aux_sym_operator_expression_repeat1,
    STATE(66), 2,
      sym__expression,
      sym_operator_expression,
    STATE(28), 5,
      sym__primary,
      sym__symbol_operand,
      sym_compound,
      sym_sequence,
      sym_group,
  [415] = 11,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_LPAREN2,
    ACTIONS(29), 1,
      sym_atom,
    ACTIONS(31), 1,
      sym_symbol,
    ACTIONS(33), 1,
      sym_number,
    ACTIONS(35), 1,
      anon_sym_SQUOTE,
    STATE(33), 1,
      sym_quoted_atom,
    STATE(15), 2,
      sym__prefix_operator,
      aux_sym_operator_expression_repeat1,
    STATE(58), 2,
      sym__expression,
      sym_operator_expression,
    STATE(28), 5,
      sym__primary,
      sym__symbol_operand,
      sym_compound,
      sym_sequence,
      sym_group,
  [455] = 11,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_LPAREN2,
    ACTIONS(29), 1,
      sym_atom,
    ACTIONS(31), 1,
      sym_symbol,
    ACTIONS(33), 1,
      sym_number,
    ACTIONS(35), 1,
      anon_sym_SQUOTE,
    STATE(33), 1,
      sym_quoted_atom,
    STATE(15), 2,
      sym__prefix_operator,
      aux_sym_operator_expression_repeat1,
    STATE(67), 2,
      sym__expression,
      sym_operator_expression,
    STATE(28), 5,
      sym__primary,
      sym__symbol_operand,
      sym_compound,
      sym_sequence,
      sym_group,
  [495] = 11,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_LPAREN2,
    ACTIONS(29), 1,
      sym_atom,
    ACTIONS(31), 1,
      sym_symbol,
    ACTIONS(33), 1,
      sym_number,
    ACTIONS(35), 1,
      anon_sym_SQUOTE,
    STATE(33), 1,
      sym_quoted_atom,
    STATE(15), 2,
      sym__prefix_operator,
      aux_sym_operator_expression_repeat1,
    STATE(69), 2,
      sym__expression,
      sym_operator_expression,
    STATE(28), 5,
      sym__primary,
      sym__symbol_operand,
      sym_compound,
      sym_sequence,
      sym_group,
  [535] = 10,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_LPAREN2,
    ACTIONS(29), 1,
      sym_atom,
    ACTIONS(31), 1,
      sym_symbol,
    ACTIONS(35), 1,
      anon_sym_SQUOTE,
    ACTIONS(71), 1,
      sym_number,
    STATE(33), 1,
      sym_quoted_atom,
    STATE(38), 2,
      sym__prefix_operator,
      aux_sym_operator_expression_repeat1,
    STATE(26), 5,
      sym__primary,
      sym__symbol_operand,
      sym_compound,
      sym_sequence,
      sym_group,
  [571] = 10,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_LPAREN2,
    ACTIONS(29), 1,
      sym_atom,
    ACTIONS(31), 1,
      sym_symbol,
    ACTIONS(35), 1,
      anon_sym_SQUOTE,
    ACTIONS(73), 1,
      sym_number,
    STATE(33), 1,
      sym_quoted_atom,
    STATE(17), 2,
      sym__prefix_operator,
      aux_sym_operator_expression_repeat1,
    STATE(43), 5,
      sym__primary,
      sym__symbol_operand,
      sym_compound,
      sym_sequence,
      sym_group,
  [607] = 10,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_LPAREN2,
    ACTIONS(29), 1,
      sym_atom,
    ACTIONS(31), 1,
      sym_symbol,
    ACTIONS(35), 1,
      anon_sym_SQUOTE,
    ACTIONS(75), 1,
      sym_number,
    STATE(33), 1,
      sym_quoted_atom,
    STATE(38), 2,
      sym__prefix_operator,
      aux_sym_operator_expression_repeat1,
    STATE(42), 5,
      sym__primary,
      sym__symbol_operand,
      sym_compound,
      sym_sequence,
      sym_group,
  [643] = 7,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(79), 1,
      anon_sym_LPAREN,
    ACTIONS(83), 1,
      anon_sym_LPAREN2,
    ACTIONS(85), 1,
      sym_atom,
    ACTIONS(88), 1,
      sym_symbol,
    ACTIONS(81), 3,
      anon_sym_LBRACK,
      sym_number,
      anon_sym_SQUOTE,
    ACTIONS(77), 6,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [672] = 7,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(79), 1,
      anon_sym_LPAREN,
    ACTIONS(83), 1,
      anon_sym_LPAREN2,
    ACTIONS(93), 1,
      sym_atom,
    ACTIONS(96), 1,
      sym_symbol,
    ACTIONS(81), 3,
      anon_sym_LBRACK,
      sym_number,
      anon_sym_SQUOTE,
    ACTIONS(91), 6,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [701] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(99), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(101), 8,
      sym_escape,
      anon_sym_AT_LBRACE,
      anon_sym_AT_LT,
      anon_sym_AT,
      anon_sym_AT_GT,
      anon_sym_AT_PIPE,
      anon_sym_AT_LBRACK,
      sym_block_close,
  [719] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(103), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(105), 8,
      sym_escape,
      anon_sym_AT_LBRACE,
      anon_sym_AT_LT,
      anon_sym_AT,
      anon_sym_AT_GT,
      anon_sym_AT_PIPE,
      anon_sym_AT_LBRACK,
      sym_block_close,
  [737] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(107), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(109), 8,
      sym_escape,
      anon_sym_AT_LBRACE,
      anon_sym_AT_LT,
      anon_sym_AT,
      anon_sym_AT_GT,
      anon_sym_AT_PIPE,
      anon_sym_AT_LBRACK,
      sym_block_close,
  [755] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(111), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(113), 8,
      sym_escape,
      anon_sym_AT_LBRACE,
      anon_sym_AT_LT,
      anon_sym_AT,
      anon_sym_AT_GT,
      anon_sym_AT_PIPE,
      anon_sym_AT_LBRACK,
      sym_block_close,
  [773] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(115), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(117), 8,
      sym_escape,
      anon_sym_AT_LBRACE,
      anon_sym_AT_LT,
      anon_sym_AT,
      anon_sym_AT_GT,
      anon_sym_AT_PIPE,
      anon_sym_AT_LBRACK,
      sym_block_close,
  [791] = 6,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(121), 1,
      sym_atom,
    ACTIONS(123), 1,
      sym_symbol,
    STATE(16), 1,
      sym__infix_operator,
    STATE(31), 1,
      aux_sym_operator_expression_repeat2,
    ACTIONS(119), 6,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [815] = 6,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(121), 1,
      sym_atom,
    ACTIONS(123), 1,
      sym_symbol,
    STATE(16), 1,
      sym__infix_operator,
    STATE(32), 1,
      aux_sym_operator_expression_repeat2,
    ACTIONS(119), 6,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [839] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(125), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(127), 8,
      sym_escape,
      anon_sym_AT_LBRACE,
      anon_sym_AT_LT,
      anon_sym_AT,
      anon_sym_AT_GT,
      anon_sym_AT_PIPE,
      anon_sym_AT_LBRACK,
      sym_block_close,
  [857] = 6,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(121), 1,
      sym_atom,
    ACTIONS(123), 1,
      sym_symbol,
    STATE(16), 1,
      sym__infix_operator,
    STATE(25), 1,
      aux_sym_operator_expression_repeat2,
    ACTIONS(129), 6,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [881] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(131), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(133), 8,
      sym_escape,
      anon_sym_AT_LBRACE,
      anon_sym_AT_LT,
      anon_sym_AT,
      anon_sym_AT_GT,
      anon_sym_AT_PIPE,
      anon_sym_AT_LBRACK,
      sym_block_close,
  [899] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(135), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(137), 8,
      sym_escape,
      anon_sym_AT_LBRACE,
      anon_sym_AT_LT,
      anon_sym_AT,
      anon_sym_AT_GT,
      anon_sym_AT_PIPE,
      anon_sym_AT_LBRACK,
      sym_block_close,
  [917] = 6,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(141), 1,
      sym_atom,
    ACTIONS(144), 1,
      sym_symbol,
    STATE(16), 1,
      sym__infix_operator,
    STATE(31), 1,
      aux_sym_operator_expression_repeat2,
    ACTIONS(139), 6,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [941] = 6,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(121), 1,
      sym_atom,
    ACTIONS(123), 1,
      sym_symbol,
    STATE(16), 1,
      sym__infix_operator,
    STATE(31), 1,
      aux_sym_operator_expression_repeat2,
    ACTIONS(147), 6,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [965] = 4,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(149), 1,
      anon_sym_LPAREN,
    ACTIONS(151), 1,
      sym_symbol,
    ACTIONS(77), 7,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      sym_atom,
  [984] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(155), 1,
      sym_symbol,
    ACTIONS(153), 8,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      sym_atom,
  [1001] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(159), 1,
      sym_symbol,
    ACTIONS(157), 8,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      sym_atom,
  [1018] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(163), 1,
      sym_symbol,
    ACTIONS(161), 7,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      sym_atom,
  [1034] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(167), 1,
      sym_symbol,
    ACTIONS(165), 7,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      sym_atom,
  [1050] = 5,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(171), 1,
      sym_atom,
    ACTIONS(174), 1,
      sym_symbol,
    STATE(38), 2,
      sym__prefix_operator,
      aux_sym_operator_expression_repeat1,
    ACTIONS(169), 4,
      anon_sym_LBRACK,
      anon_sym_LPAREN2,
      sym_number,
      anon_sym_SQUOTE,
  [1070] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(179), 1,
      sym_symbol,
    ACTIONS(177), 7,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      sym_atom,
  [1086] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(183), 1,
      sym_symbol,
    ACTIONS(181), 7,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      sym_atom,
  [1102] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(187), 1,
      sym_symbol,
    ACTIONS(185), 7,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      sym_atom,
  [1118] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(191), 1,
      sym_symbol,
    ACTIONS(189), 7,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      sym_atom,
  [1134] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(193), 1,
      sym_symbol,
    ACTIONS(139), 7,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      sym_atom,
  [1150] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(197), 1,
      sym_symbol,
    ACTIONS(195), 7,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      sym_atom,
  [1166] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(201), 1,
      sym_symbol,
    ACTIONS(199), 7,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      sym_atom,
  [1182] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(205), 1,
      sym_symbol,
    ACTIONS(203), 7,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      sym_atom,
  [1198] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(83), 1,
      sym_symbol,
    ACTIONS(81), 5,
      anon_sym_LBRACK,
      anon_sym_LPAREN2,
      sym_atom,
      sym_number,
      anon_sym_SQUOTE,
  [1212] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(209), 1,
      sym_symbol,
    ACTIONS(207), 5,
      anon_sym_LBRACK,
      anon_sym_LPAREN2,
      sym_atom,
      sym_number,
      anon_sym_SQUOTE,
  [1226] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(213), 1,
      sym_symbol,
    ACTIONS(211), 5,
      anon_sym_LBRACK,
      anon_sym_LPAREN2,
      sym_atom,
      sym_number,
      anon_sym_SQUOTE,
  [1240] = 4,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(217), 1,
      anon_sym_SQUOTE2,
    STATE(53), 1,
      aux_sym_quoted_atom_repeat1,
    ACTIONS(215), 2,
      aux_sym_quoted_atom_token1,
      sym_escape_sequence,
  [1254] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(221), 1,
      anon_sym_SEMI,
    STATE(52), 1,
      aux_sym__facts_repeat1,
    ACTIONS(219), 2,
      anon_sym_RBRACE,
      anon_sym_PIPE,
  [1268] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(221), 1,
      anon_sym_SEMI,
    STATE(54), 1,
      aux_sym__facts_repeat1,
    ACTIONS(223), 2,
      anon_sym_RBRACE,
      anon_sym_PIPE,
  [1282] = 4,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(228), 1,
      anon_sym_SQUOTE2,
    STATE(53), 1,
      aux_sym_quoted_atom_repeat1,
    ACTIONS(225), 2,
      aux_sym_quoted_atom_token1,
      sym_escape_sequence,
  [1296] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(232), 1,
      anon_sym_SEMI,
    STATE(54), 1,
      aux_sym__facts_repeat1,
    ACTIONS(230), 2,
      anon_sym_RBRACE,
      anon_sym_PIPE,
  [1310] = 4,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(237), 1,
      anon_sym_SQUOTE2,
    STATE(50), 1,
      aux_sym_quoted_atom_repeat1,
    ACTIONS(235), 2,
      aux_sym_quoted_atom_token1,
      sym_escape_sequence,
  [1324] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(239), 1,
      anon_sym_LT,
    ACTIONS(241), 1,
      anon_sym_GT,
    ACTIONS(243), 1,
      anon_sym_PIPE2,
  [1337] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(245), 1,
      anon_sym_COMMA,
    ACTIONS(248), 1,
      anon_sym_RBRACK,
    STATE(57), 1,
      aux_sym_sequence_repeat1,
  [1350] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(250), 1,
      anon_sym_COMMA,
    ACTIONS(252), 1,
      anon_sym_RPAREN,
    STATE(64), 1,
      aux_sym_compound_repeat1,
  [1363] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_PIPE2,
  [1372] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(230), 3,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_SEMI,
  [1381] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(250), 1,
      anon_sym_COMMA,
    ACTIONS(256), 1,
      anon_sym_RPAREN,
    STATE(65), 1,
      aux_sym_compound_repeat1,
  [1394] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 1,
      anon_sym_COMMA,
    ACTIONS(260), 1,
      anon_sym_RBRACK,
    STATE(63), 1,
      aux_sym_sequence_repeat1,
  [1407] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 1,
      anon_sym_COMMA,
    ACTIONS(262), 1,
      anon_sym_RBRACK,
    STATE(57), 1,
      aux_sym_sequence_repeat1,
  [1420] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(250), 1,
      anon_sym_COMMA,
    ACTIONS(264), 1,
      anon_sym_RPAREN,
    STATE(65), 1,
      aux_sym_compound_repeat1,
  [1433] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(266), 1,
      anon_sym_COMMA,
    ACTIONS(269), 1,
      anon_sym_RPAREN,
    STATE(65), 1,
      aux_sym_compound_repeat1,
  [1446] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(250), 1,
      anon_sym_COMMA,
    ACTIONS(271), 1,
      anon_sym_RPAREN,
    STATE(61), 1,
      aux_sym_compound_repeat1,
  [1459] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(273), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1467] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(275), 1,
      aux_sym__label_token1,
    STATE(56), 1,
      sym__label,
  [1477] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(277), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1485] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(279), 1,
      anon_sym_PIPE,
  [1492] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(281), 1,
      anon_sym_RPAREN,
  [1499] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(283), 1,
      anon_sym_RBRACE,
  [1506] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(285), 1,
      anon_sym_PIPE,
  [1513] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(287), 1,
      anon_sym_PIPE,
  [1520] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(289), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 43,
  [SMALL_STATE(4)] = 86,
  [SMALL_STATE(5)] = 129,
  [SMALL_STATE(6)] = 172,
  [SMALL_STATE(7)] = 215,
  [SMALL_STATE(8)] = 255,
  [SMALL_STATE(9)] = 295,
  [SMALL_STATE(10)] = 335,
  [SMALL_STATE(11)] = 375,
  [SMALL_STATE(12)] = 415,
  [SMALL_STATE(13)] = 455,
  [SMALL_STATE(14)] = 495,
  [SMALL_STATE(15)] = 535,
  [SMALL_STATE(16)] = 571,
  [SMALL_STATE(17)] = 607,
  [SMALL_STATE(18)] = 643,
  [SMALL_STATE(19)] = 672,
  [SMALL_STATE(20)] = 701,
  [SMALL_STATE(21)] = 719,
  [SMALL_STATE(22)] = 737,
  [SMALL_STATE(23)] = 755,
  [SMALL_STATE(24)] = 773,
  [SMALL_STATE(25)] = 791,
  [SMALL_STATE(26)] = 815,
  [SMALL_STATE(27)] = 839,
  [SMALL_STATE(28)] = 857,
  [SMALL_STATE(29)] = 881,
  [SMALL_STATE(30)] = 899,
  [SMALL_STATE(31)] = 917,
  [SMALL_STATE(32)] = 941,
  [SMALL_STATE(33)] = 965,
  [SMALL_STATE(34)] = 984,
  [SMALL_STATE(35)] = 1001,
  [SMALL_STATE(36)] = 1018,
  [SMALL_STATE(37)] = 1034,
  [SMALL_STATE(38)] = 1050,
  [SMALL_STATE(39)] = 1070,
  [SMALL_STATE(40)] = 1086,
  [SMALL_STATE(41)] = 1102,
  [SMALL_STATE(42)] = 1118,
  [SMALL_STATE(43)] = 1134,
  [SMALL_STATE(44)] = 1150,
  [SMALL_STATE(45)] = 1166,
  [SMALL_STATE(46)] = 1182,
  [SMALL_STATE(47)] = 1198,
  [SMALL_STATE(48)] = 1212,
  [SMALL_STATE(49)] = 1226,
  [SMALL_STATE(50)] = 1240,
  [SMALL_STATE(51)] = 1254,
  [SMALL_STATE(52)] = 1268,
  [SMALL_STATE(53)] = 1282,
  [SMALL_STATE(54)] = 1296,
  [SMALL_STATE(55)] = 1310,
  [SMALL_STATE(56)] = 1324,
  [SMALL_STATE(57)] = 1337,
  [SMALL_STATE(58)] = 1350,
  [SMALL_STATE(59)] = 1363,
  [SMALL_STATE(60)] = 1372,
  [SMALL_STATE(61)] = 1381,
  [SMALL_STATE(62)] = 1394,
  [SMALL_STATE(63)] = 1407,
  [SMALL_STATE(64)] = 1420,
  [SMALL_STATE(65)] = 1433,
  [SMALL_STATE(66)] = 1446,
  [SMALL_STATE(67)] = 1459,
  [SMALL_STATE(68)] = 1467,
  [SMALL_STATE(69)] = 1477,
  [SMALL_STATE(70)] = 1485,
  [SMALL_STATE(71)] = 1492,
  [SMALL_STATE(72)] = 1499,
  [SMALL_STATE(73)] = 1506,
  [SMALL_STATE(74)] = 1513,
  [SMALL_STATE(75)] = 1520,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [50] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [56] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [59] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(68),
  [62] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [65] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [68] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__primary, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__prefix_operator, 1, 0, 1),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__prefix_operator, 1, 0, 1),
  [85] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym__prefix_operator, 1, 0, 1), REDUCE(sym__primary, 1, 0, 0),
  [88] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym__prefix_operator, 1, 0, 1), REDUCE(sym__primary, 1, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__symbol_operand, 1, -1, 0),
  [93] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym__prefix_operator, 1, 0, 1), REDUCE(sym__symbol_operand, 1, -1, 0),
  [96] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym__prefix_operator, 1, 0, 1), REDUCE(sym__symbol_operand, 1, -1, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_region_close, 3, 0, 3),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_region_close, 3, 0, 3),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_region_open, 5, 0, 3),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_region_open, 5, 0, 3),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_region_open, 3, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_region_open, 3, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_point, 3, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_point, 3, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_region_close, 1, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_region_close, 1, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operator_expression, 2, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [123] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_region_split, 1, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_region_split, 1, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_region_split, 3, 0, 3),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_region_split, 3, 0, 3),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_open, 3, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_open, 3, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_operator_expression_repeat2, 2, 0, 0),
  [141] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_operator_expression_repeat2, 2, 0, 0), SHIFT_REPEAT(48),
  [144] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_operator_expression_repeat2, 2, 0, 0), SHIFT_REPEAT(49),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operator_expression, 3, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__primary, 1, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_atom, 2, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_atom, 2, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_atom, 3, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_atom, 3, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sequence, 4, 0, 5),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sequence, 4, 0, 5),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compound, 5, 0, 12),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_compound, 5, 0, 12),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_operator_expression_repeat1, 2, 0, 0),
  [171] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_operator_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [174] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_operator_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sequence, 3, 0, 4),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sequence, 3, 0, 4),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group, 3, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_group, 3, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sequence, 2, 0, 0),
  [187] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sequence, 2, 0, 0),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_operator_expression_repeat2, 3, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_operator_expression_repeat2, 3, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_operator_expression_repeat2, 2, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compound, 4, 0, 8),
  [197] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_compound, 4, 0, 8),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compound, 4, 0, 7),
  [201] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_compound, 4, 0, 7),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compound, 5, 0, 10),
  [205] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_compound, 5, 0, 10),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__infix_operator, 1, 1, 1),
  [209] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__infix_operator, 1, 1, 1),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__infix_operator, 1, 2, 1),
  [213] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__infix_operator, 1, 2, 1),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [217] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__facts, 1, 0, 0),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__facts, 2, 0, 0),
  [225] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quoted_atom_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [228] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quoted_atom_repeat1, 2, 0, 0),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__facts_repeat1, 2, 0, 0),
  [232] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__facts_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [237] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [245] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sequence_repeat1, 2, 0, 6), SHIFT_REPEAT(13),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sequence_repeat1, 2, 0, 6),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [254] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__label, 1, 0, 2),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [266] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_compound_repeat1, 2, 0, 11), SHIFT_REPEAT(14),
  [269] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_compound_repeat1, 2, 0, 11),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [273] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sequence_repeat1, 2, 0, 4),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [277] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_compound_repeat1, 2, 0, 9),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [289] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_ilk(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "ilk",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
