/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 65
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 49
#define ALIAS_COUNT 2
#define TOKEN_COUNT 27
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 10
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_text = 1,
  sym_escape = 2,
  anon_sym_AT_LBRACE = 3,
  anon_sym_RBRACE = 4,
  anon_sym_AT_LT = 5,
  anon_sym_AT = 6,
  anon_sym_LT = 7,
  anon_sym_PIPE = 8,
  anon_sym_AT_GT = 9,
  anon_sym_GT = 10,
  anon_sym_AT_LBRACK = 11,
  sym_block_close = 12,
  aux_sym__label_token1 = 13,
  anon_sym_SEMI = 14,
  anon_sym_LPAREN = 15,
  anon_sym_COMMA = 16,
  anon_sym_RPAREN = 17,
  anon_sym_LPAREN2 = 18,
  sym_atom = 19,
  sym_symbol = 20,
  sym_number = 21,
  anon_sym_SQUOTE = 22,
  aux_sym_quoted_atom_token1 = 23,
  anon_sym_SQUOTE2 = 24,
  sym_escape_sequence = 25,
  sym_comment = 26,
  sym_document = 27,
  sym_point = 28,
  sym_region_open = 29,
  sym_region_close = 30,
  sym_block_open = 31,
  sym__label = 32,
  sym__facts = 33,
  sym__expression = 34,
  sym_operator_expression = 35,
  sym__prefix_operator = 36,
  sym__infix_operator = 37,
  sym__primary = 38,
  sym__symbol_operand = 39,
  sym_compound = 40,
  sym_group = 41,
  sym_quoted_atom = 42,
  aux_sym_document_repeat1 = 43,
  aux_sym__facts_repeat1 = 44,
  aux_sym_operator_expression_repeat1 = 45,
  aux_sym_operator_expression_repeat2 = 46,
  aux_sym_compound_repeat1 = 47,
  aux_sym_quoted_atom_repeat1 = 48,
  alias_sym_functor = 49,
  alias_sym_operator = 50,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_text] = "text",
  [sym_escape] = "escape",
  [anon_sym_AT_LBRACE] = "@{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_AT_LT] = "@<",
  [anon_sym_AT] = "@",
  [anon_sym_LT] = "<",
  [anon_sym_PIPE] = "|",
  [anon_sym_AT_GT] = "@>",
  [anon_sym_GT] = ">",
  [anon_sym_AT_LBRACK] = "@[",
  [sym_block_close] = "block_close",
  [aux_sym__label_token1] = "label",
  [anon_sym_SEMI] = ";",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LPAREN2] = "(",
  [sym_atom] = "atom",
  [sym_symbol] = "symbol",
  [sym_number] = "number",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_quoted_atom_token1] = "quoted_atom_token1",
  [anon_sym_SQUOTE2] = "'",
  [sym_escape_sequence] = "escape_sequence",
  [sym_comment] = "comment",
  [sym_document] = "document",
  [sym_point] = "point",
  [sym_region_open] = "region_open",
  [sym_region_close] = "region_close",
  [sym_block_open] = "block_open",
  [sym__label] = "_label",
  [sym__facts] = "_facts",
  [sym__expression] = "_expression",
  [sym_operator_expression] = "operator_expression",
  [sym__prefix_operator] = "_prefix_operator",
  [sym__infix_operator] = "_infix_operator",
  [sym__primary] = "_primary",
  [sym__symbol_operand] = "_symbol_operand",
  [sym_compound] = "compound",
  [sym_group] = "group",
  [sym_quoted_atom] = "quoted_atom",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym__facts_repeat1] = "_facts_repeat1",
  [aux_sym_operator_expression_repeat1] = "operator_expression_repeat1",
  [aux_sym_operator_expression_repeat2] = "operator_expression_repeat2",
  [aux_sym_compound_repeat1] = "compound_repeat1",
  [aux_sym_quoted_atom_repeat1] = "quoted_atom_repeat1",
  [alias_sym_functor] = "functor",
  [alias_sym_operator] = "operator",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_text] = sym_text,
  [sym_escape] = sym_escape,
  [anon_sym_AT_LBRACE] = anon_sym_AT_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_AT_LT] = anon_sym_AT_LT,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_AT_GT] = anon_sym_AT_GT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_AT_LBRACK] = anon_sym_AT_LBRACK,
  [sym_block_close] = sym_block_close,
  [aux_sym__label_token1] = aux_sym__label_token1,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LPAREN2] = anon_sym_LPAREN,
  [sym_atom] = sym_atom,
  [sym_symbol] = sym_symbol,
  [sym_number] = sym_number,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_quoted_atom_token1] = aux_sym_quoted_atom_token1,
  [anon_sym_SQUOTE2] = anon_sym_SQUOTE,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_comment] = sym_comment,
  [sym_document] = sym_document,
  [sym_point] = sym_point,
  [sym_region_open] = sym_region_open,
  [sym_region_close] = sym_region_close,
  [sym_block_open] = sym_block_open,
  [sym__label] = sym__label,
  [sym__facts] = sym__facts,
  [sym__expression] = sym__expression,
  [sym_operator_expression] = sym_operator_expression,
  [sym__prefix_operator] = sym__prefix_operator,
  [sym__infix_operator] = sym__infix_operator,
  [sym__primary] = sym__primary,
  [sym__symbol_operand] = sym__symbol_operand,
  [sym_compound] = sym_compound,
  [sym_group] = sym_group,
  [sym_quoted_atom] = sym_quoted_atom,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym__facts_repeat1] = aux_sym__facts_repeat1,
  [aux_sym_operator_expression_repeat1] = aux_sym_operator_expression_repeat1,
  [aux_sym_operator_expression_repeat2] = aux_sym_operator_expression_repeat2,
  [aux_sym_compound_repeat1] = aux_sym_compound_repeat1,
  [aux_sym_quoted_atom_repeat1] = aux_sym_quoted_atom_repeat1,
  [alias_sym_functor] = alias_sym_functor,
  [alias_sym_operator] = alias_sym_operator,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_escape] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AT_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_block_close] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__label_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN2] = {
    .visible = true,
    .named = false,
  },
  [sym_atom] = {
    .visible = true,
    .named = true,
  },
  [sym_symbol] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_atom_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE2] = {
    .visible = true,
    .named = false,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_point] = {
    .visible = true,
    .named = true,
  },
  [sym_region_open] = {
    .visible = true,
    .named = true,
  },
  [sym_region_close] = {
    .visible = true,
    .named = true,
  },
  [sym_block_open] = {
    .visible = true,
    .named = true,
  },
  [sym__label] = {
    .visible = false,
    .named = true,
  },
  [sym__facts] = {
    .visible = false,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_operator_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__prefix_operator] = {
    .visible = false,
    .named = true,
  },
  [sym__infix_operator] = {
    .visible = false,
    .named = true,
  },
  [sym__primary] = {
    .visible = false,
    .named = true,
  },
  [sym__symbol_operand] = {
    .visible = false,
    .named = true,
  },
  [sym_compound] = {
    .visible = true,
    .named = true,
  },
  [sym_group] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_atom] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__facts_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_operator_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_operator_expression_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_compound_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quoted_atom_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_functor] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_operator] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_argument = 1,
  field_functor = 2,
  field_label = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_argument] = "argument",
  [field_functor] = "functor",
  [field_label] = "label",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [2] = {.index = 0, .length = 1},
  [3] = {.index = 1, .length = 1},
  [4] = {.index = 2, .length = 2},
  [5] = {.index = 2, .length = 2},
  [6] = {.index = 4, .length = 1},
  [7] = {.index = 5, .length = 3},
  [8] = {.index = 8, .length = 2},
  [9] = {.index = 5, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_label, 0},
  [1] =
    {field_label, 1, .inherited = true},
  [2] =
    {field_argument, 2},
    {field_functor, 0},
  [4] =
    {field_argument, 1},
  [5] =
    {field_argument, 2},
    {field_argument, 3, .inherited = true},
    {field_functor, 0},
  [8] =
    {field_argument, 0, .inherited = true},
    {field_argument, 1, .inherited = true},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = alias_sym_operator,
  },
  [4] = {
    [0] = alias_sym_functor,
  },
  [7] = {
    [0] = alias_sym_functor,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
};

static const TSCharacterRange sym_symbol_character_set_1[] = {
  {'&', '&'}, {'*', '+'}, {'-', '/'}, {':', ':'}, {'<', '>'}, {'@', '@'}, {'\\', '\\'}, {'^', '^'},
  {'~', '~'},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(29);
      ADVANCE_MAP(
        '\'', 71,
        '(', 50,
        ')', 52,
        ',', 51,
        '-', 14,
        '/', 7,
        ';', 49,
        '<', 40,
        '>', 43,
        '@', 39,
        '|', 41,
        '}', 37,
        '#', 48,
        '$', 48,
        '?', 48,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(27);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(62);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 1:
      if (lookahead == ' ') ADVANCE(66);
      if (lookahead == '\'') ADVANCE(72);
      if (lookahead == '/') ADVANCE(69);
      if (lookahead == '\\') ADVANCE(12);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(11);
      if (lookahead > ' ' &&
          lookahead != 0x7f &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(70);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '\'', 65,
        '(', 50,
        ')', 52,
        ',', 51,
        '-', 60,
        '/', 57,
        ';', 49,
        '|', 41,
        '}', 37,
        '#', 56,
        '$', 56,
        '?', 56,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(62);
      if (('&' <= lookahead && lookahead <= '@') ||
          lookahead == '\\' ||
          lookahead == '^' ||
          lookahead == '~') ADVANCE(61);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '\'', 65,
        '(', 53,
        ')', 52,
        ',', 51,
        '-', 60,
        '/', 57,
        ';', 49,
        '|', 41,
        '}', 37,
        '#', 56,
        '$', 56,
        '?', 56,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(62);
      if (('&' <= lookahead && lookahead <= '@') ||
          lookahead == '\\' ||
          lookahead == '^' ||
          lookahead == '~') ADVANCE(61);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 4:
      if (lookahead == '\'') ADVANCE(65);
      if (lookahead == '(') ADVANCE(53);
      if (lookahead == '-') ADVANCE(60);
      if (lookahead == '/') ADVANCE(57);
      if (lookahead == '#' ||
          lookahead == '$' ||
          lookahead == '?') ADVANCE(56);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(62);
      if (lookahead == '&' ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('.' <= lookahead && lookahead <= ':') ||
          ('<' <= lookahead && lookahead <= '@') ||
          lookahead == '\\' ||
          lookahead == '^' ||
          lookahead == '~') ADVANCE(61);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 5:
      ADVANCE_MAP(
        '(', 50,
        ')', 52,
        ',', 51,
        '/', 57,
        ';', 49,
        '|', 41,
        '}', 37,
        '#', 56,
        '$', 56,
        '?', 56,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (lookahead == '&' ||
          ('*' <= lookahead && lookahead <= '.') ||
          (':' <= lookahead && lookahead <= '@') ||
          lookahead == '\\' ||
          lookahead == '^' ||
          lookahead == '~') ADVANCE(61);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 6:
      ADVANCE_MAP(
        ')', 52,
        ',', 51,
        '/', 57,
        ';', 49,
        '|', 41,
        '}', 37,
        '#', 56,
        '$', 56,
        '?', 56,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (lookahead == '&' ||
          ('*' <= lookahead && lookahead <= '.') ||
          (':' <= lookahead && lookahead <= '@') ||
          lookahead == '\\' ||
          lookahead == '^' ||
          lookahead == '~') ADVANCE(61);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 7:
      if (lookahead == '*') ADVANCE(9);
      END_STATE();
    case 8:
      if (lookahead == '*') ADVANCE(8);
      if (lookahead == '/') ADVANCE(74);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(9);
      END_STATE();
    case 9:
      if (lookahead == '*') ADVANCE(8);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == '/') ADVANCE(7);
      if (lookahead == '#' ||
          lookahead == '$' ||
          lookahead == '?') ADVANCE(48);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(11);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 11:
      if (lookahead == '/') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(11);
      END_STATE();
    case 12:
      if (lookahead == 'U') ADVANCE(24);
      if (lookahead == 'u') ADVANCE(20);
      if (lookahead == '\'' ||
          lookahead == '\\' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't') ADVANCE(73);
      END_STATE();
    case 13:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(64);
      END_STATE();
    case 14:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(62);
      END_STATE();
    case 15:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(63);
      END_STATE();
    case 16:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(64);
      END_STATE();
    case 17:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(73);
      END_STATE();
    case 18:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(17);
      END_STATE();
    case 19:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(18);
      END_STATE();
    case 20:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(19);
      END_STATE();
    case 21:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(20);
      END_STATE();
    case 22:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(21);
      END_STATE();
    case 23:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(22);
      END_STATE();
    case 24:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(23);
      END_STATE();
    case 25:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 26:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 27:
      if (eof) ADVANCE(29);
      ADVANCE_MAP(
        '\'', 65,
        '(', 53,
        ')', 52,
        ',', 51,
        '-', 14,
        '/', 7,
        ';', 49,
        '@', 39,
        '|', 41,
        '}', 37,
        '#', 56,
        '$', 56,
        '?', 56,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(27);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(62);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 28:
      if (eof) ADVANCE(29);
      if (lookahead == '/') ADVANCE(32);
      if (lookahead == '@') ADVANCE(39);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(33);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(34);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '*') ADVANCE(30);
      if (lookahead == '/') ADVANCE(34);
      if (lookahead != 0 &&
          lookahead != '@' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(31);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '*') ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '@' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '*') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '@' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(34);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '/') ADVANCE(32);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(33);
      if (lookahead != 0 &&
          lookahead != '@' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(34);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '@' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_escape);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_AT_LBRACE);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_AT_LT);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_AT);
      if (lookahead == '<') ADVANCE(38);
      if (lookahead == '>') ADVANCE(42);
      if (lookahead == '@') ADVANCE(35);
      if (lookahead == '[') ADVANCE(44);
      if (lookahead == ']') ADVANCE(45);
      if (lookahead == '{') ADVANCE(36);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_AT_GT);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_AT_LBRACK);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_block_close);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym__label_token1);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym__label_token1);
      if (lookahead == '_') ADVANCE(25);
      if (lookahead == '#' ||
          lookahead == '$' ||
          lookahead == '?') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym__label_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_LPAREN2);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_atom);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == '_') ADVANCE(26);
      if (lookahead == '#' ||
          lookahead == '$' ||
          lookahead == '?') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_atom);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == '*') ADVANCE(59);
      if (set_contains(sym_symbol_character_set_1, 9, lookahead)) ADVANCE(61);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == '*') ADVANCE(58);
      if (lookahead == '/') ADVANCE(61);
      if (set_contains(sym_symbol_character_set_1, 9, lookahead)) ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(9);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == '*') ADVANCE(58);
      if (set_contains(sym_symbol_character_set_1, 9, lookahead)) ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(9);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_symbol);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(62);
      if (set_contains(sym_symbol_character_set_1, 9, lookahead)) ADVANCE(61);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_symbol);
      if (set_contains(sym_symbol_character_set_1, 9, lookahead)) ADVANCE(61);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(15);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(62);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(64);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(aux_sym_quoted_atom_token1);
      if (lookahead == ' ') ADVANCE(66);
      if (lookahead == '/') ADVANCE(69);
      if (lookahead > ' ' &&
          lookahead != '\'' &&
          lookahead != '\\' &&
          lookahead != 0x7f &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(70);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(aux_sym_quoted_atom_token1);
      if (lookahead == '*') ADVANCE(67);
      if (lookahead == '/') ADVANCE(70);
      if (lookahead > 0x1f &&
          lookahead != '\'' &&
          lookahead != '\\' &&
          lookahead != 0x7f &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(68);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(aux_sym_quoted_atom_token1);
      if (lookahead == '*') ADVANCE(67);
      if (lookahead > 0x1f &&
          lookahead != '\'' &&
          lookahead != '\\' &&
          lookahead != 0x7f &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(68);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(aux_sym_quoted_atom_token1);
      if (lookahead == '*') ADVANCE(68);
      if (lookahead > 0x1f &&
          lookahead != '\'' &&
          lookahead != '\\' &&
          lookahead != 0x7f &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(70);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(aux_sym_quoted_atom_token1);
      if (lookahead > 0x1f &&
          lookahead != '\'' &&
          lookahead != '\\' &&
          lookahead != 0x7f &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(70);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_SQUOTE2);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_SQUOTE2);
      if (lookahead == '\'') ADVANCE(73);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 28},
  [2] = {.lex_state = 4},
  [3] = {.lex_state = 4},
  [4] = {.lex_state = 4},
  [5] = {.lex_state = 4},
  [6] = {.lex_state = 28},
  [7] = {.lex_state = 4},
  [8] = {.lex_state = 28},
  [9] = {.lex_state = 4},
  [10] = {.lex_state = 4},
  [11] = {.lex_state = 4},
  [12] = {.lex_state = 4},
  [13] = {.lex_state = 4},
  [14] = {.lex_state = 4},
  [15] = {.lex_state = 4},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 5},
  [19] = {.lex_state = 5},
  [20] = {.lex_state = 28},
  [21] = {.lex_state = 28},
  [22] = {.lex_state = 5},
  [23] = {.lex_state = 28},
  [24] = {.lex_state = 28},
  [25] = {.lex_state = 5},
  [26] = {.lex_state = 28},
  [27] = {.lex_state = 5},
  [28] = {.lex_state = 28},
  [29] = {.lex_state = 5},
  [30] = {.lex_state = 5},
  [31] = {.lex_state = 5},
  [32] = {.lex_state = 4},
  [33] = {.lex_state = 5},
  [34] = {.lex_state = 5},
  [35] = {.lex_state = 5},
  [36] = {.lex_state = 5},
  [37] = {.lex_state = 5},
  [38] = {.lex_state = 5},
  [39] = {.lex_state = 5},
  [40] = {.lex_state = 4},
  [41] = {.lex_state = 4},
  [42] = {.lex_state = 4},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 10},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_escape] = ACTIONS(1),
    [anon_sym_AT_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_AT_LT] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_AT_GT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_AT_LBRACK] = ACTIONS(1),
    [sym_block_close] = ACTIONS(1),
    [aux_sym__label_token1] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LPAREN2] = ACTIONS(1),
    [sym_atom] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE2] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_document] = STATE(60),
    [sym_point] = STATE(6),
    [sym_region_open] = STATE(6),
    [sym_region_close] = STATE(6),
    [sym_block_open] = STATE(6),
    [aux_sym_document_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_text] = ACTIONS(7),
    [sym_escape] = ACTIONS(9),
    [anon_sym_AT_LBRACE] = ACTIONS(11),
    [anon_sym_AT_LT] = ACTIONS(13),
    [anon_sym_AT] = ACTIONS(15),
    [anon_sym_AT_GT] = ACTIONS(17),
    [anon_sym_AT_LBRACK] = ACTIONS(19),
    [sym_block_close] = ACTIONS(9),
    [sym_comment] = ACTIONS(21),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_LPAREN2,
    ACTIONS(25), 1,
      sym_atom,
    ACTIONS(27), 1,
      sym_symbol,
    ACTIONS(29), 1,
      sym_number,
    ACTIONS(31), 1,
      anon_sym_SQUOTE,
    STATE(29), 1,
      sym_quoted_atom,
    STATE(61), 1,
      sym__facts,
    STATE(13), 2,
      sym__prefix_operator,
      aux_sym_operator_expression_repeat1,
    STATE(45), 2,
      sym__expression,
      sym_operator_expression,
    STATE(19), 4,
      sym__primary,
      sym__symbol_operand,
      sym_compound,
      sym_group,
  [39] = 11,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_LPAREN2,
    ACTIONS(25), 1,
      sym_atom,
    ACTIONS(27), 1,
      sym_symbol,
    ACTIONS(29), 1,
      sym_number,
    ACTIONS(31), 1,
      anon_sym_SQUOTE,
    STATE(29), 1,
      sym_quoted_atom,
    STATE(62), 1,
      sym__facts,
    STATE(13), 2,
      sym__prefix_operator,
      aux_sym_operator_expression_repeat1,
    STATE(45), 2,
      sym__expression,
      sym_operator_expression,
    STATE(19), 4,
      sym__primary,
      sym__symbol_operand,
      sym_compound,
      sym_group,
  [78] = 11,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_LPAREN2,
    ACTIONS(25), 1,
      sym_atom,
    ACTIONS(27), 1,
      sym_symbol,
    ACTIONS(29), 1,
      sym_number,
    ACTIONS(31), 1,
      anon_sym_SQUOTE,
    STATE(29), 1,
      sym_quoted_atom,
    STATE(63), 1,
      sym__facts,
    STATE(13), 2,
      sym__prefix_operator,
      aux_sym_operator_expression_repeat1,
    STATE(45), 2,
      sym__expression,
      sym_operator_expression,
    STATE(19), 4,
      sym__primary,
      sym__symbol_operand,
      sym_compound,
      sym_group,
  [117] = 11,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_LPAREN2,
    ACTIONS(25), 1,
      sym_atom,
    ACTIONS(27), 1,
      sym_symbol,
    ACTIONS(29), 1,
      sym_number,
    ACTIONS(31), 1,
      anon_sym_SQUOTE,
    STATE(29), 1,
      sym_quoted_atom,
    STATE(59), 1,
      sym__facts,
    STATE(13), 2,
      sym__prefix_operator,
      aux_sym_operator_expression_repeat1,
    STATE(45), 2,
      sym__expression,
      sym_operator_expression,
    STATE(19), 4,
      sym__primary,
      sym__symbol_operand,
      sym_compound,
      sym_group,
  [156] = 10,
    ACTIONS(11), 1,
      anon_sym_AT_LBRACE,
    ACTIONS(13), 1,
      anon_sym_AT_LT,
    ACTIONS(15), 1,
      anon_sym_AT,
    ACTIONS(17), 1,
      anon_sym_AT_GT,
    ACTIONS(19), 1,
      anon_sym_AT_LBRACK,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
    ACTIONS(35), 1,
      sym_text,
    ACTIONS(37), 2,
      sym_escape,
      sym_block_close,
    STATE(8), 5,
      sym_point,
      sym_region_open,
      sym_region_close,
      sym_block_open,
      aux_sym_document_repeat1,
  [192] = 10,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_LPAREN2,
    ACTIONS(25), 1,
      sym_atom,
    ACTIONS(27), 1,
      sym_symbol,
    ACTIONS(29), 1,
      sym_number,
    ACTIONS(31), 1,
      anon_sym_SQUOTE,
    STATE(29), 1,
      sym_quoted_atom,
    STATE(13), 2,
      sym__prefix_operator,
      aux_sym_operator_expression_repeat1,
    STATE(64), 2,
      sym__expression,
      sym_operator_expression,
    STATE(19), 4,
      sym__primary,
      sym__symbol_operand,
      sym_compound,
      sym_group,
  [228] = 10,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
    ACTIONS(41), 1,
      sym_text,
    ACTIONS(47), 1,
      anon_sym_AT_LBRACE,
    ACTIONS(50), 1,
      anon_sym_AT_LT,
    ACTIONS(53), 1,
      anon_sym_AT,
    ACTIONS(56), 1,
      anon_sym_AT_GT,
    ACTIONS(59), 1,
      anon_sym_AT_LBRACK,
    ACTIONS(44), 2,
      sym_escape,
      sym_block_close,
    STATE(8), 5,
      sym_point,
      sym_region_open,
      sym_region_close,
      sym_block_open,
      aux_sym_document_repeat1,
  [264] = 10,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_LPAREN2,
    ACTIONS(25), 1,
      sym_atom,
    ACTIONS(27), 1,
      sym_symbol,
    ACTIONS(29), 1,
      sym_number,
    ACTIONS(31), 1,
      anon_sym_SQUOTE,
    STATE(29), 1,
      sym_quoted_atom,
    STATE(13), 2,
      sym__prefix_operator,
      aux_sym_operator_expression_repeat1,
    STATE(53), 2,
      sym__expression,
      sym_operator_expression,
    STATE(19), 4,
      sym__primary,
      sym__symbol_operand,
      sym_compound,
      sym_group,
  [300] = 10,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_LPAREN2,
    ACTIONS(25), 1,
      sym_atom,
    ACTIONS(27), 1,
      sym_symbol,
    ACTIONS(29), 1,
      sym_number,
    ACTIONS(31), 1,
      anon_sym_SQUOTE,
    STATE(29), 1,
      sym_quoted_atom,
    STATE(13), 2,
      sym__prefix_operator,
      aux_sym_operator_expression_repeat1,
    STATE(54), 2,
      sym__expression,
      sym_operator_expression,
    STATE(19), 4,
      sym__primary,
      sym__symbol_operand,
      sym_compound,
      sym_group,
  [336] = 10,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_LPAREN2,
    ACTIONS(25), 1,
      sym_atom,
    ACTIONS(27), 1,
      sym_symbol,
    ACTIONS(29), 1,
      sym_number,
    ACTIONS(31), 1,
      anon_sym_SQUOTE,
    STATE(29), 1,
      sym_quoted_atom,
    STATE(13), 2,
      sym__prefix_operator,
      aux_sym_operator_expression_repeat1,
    STATE(57), 2,
      sym__expression,
      sym_operator_expression,
    STATE(19), 4,
      sym__primary,
      sym__symbol_operand,
      sym_compound,
      sym_group,
  [372] = 10,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_LPAREN2,
    ACTIONS(25), 1,
      sym_atom,
    ACTIONS(27), 1,
      sym_symbol,
    ACTIONS(29), 1,
      sym_number,
    ACTIONS(31), 1,
      anon_sym_SQUOTE,
    STATE(29), 1,
      sym_quoted_atom,
    STATE(13), 2,
      sym__prefix_operator,
      aux_sym_operator_expression_repeat1,
    STATE(50), 2,
      sym__expression,
      sym_operator_expression,
    STATE(19), 4,
      sym__primary,
      sym__symbol_operand,
      sym_compound,
      sym_group,
  [408] = 9,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_LPAREN2,
    ACTIONS(25), 1,
      sym_atom,
    ACTIONS(27), 1,
      sym_symbol,
    ACTIONS(31), 1,
      anon_sym_SQUOTE,
    ACTIONS(62), 1,
      sym_number,
    STATE(29), 1,
      sym_quoted_atom,
    STATE(32), 2,
      sym__prefix_operator,
      aux_sym_operator_expression_repeat1,
    STATE(22), 4,
      sym__primary,
      sym__symbol_operand,
      sym_compound,
      sym_group,
  [440] = 9,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_LPAREN2,
    ACTIONS(25), 1,
      sym_atom,
    ACTIONS(27), 1,
      sym_symbol,
    ACTIONS(31), 1,
      anon_sym_SQUOTE,
    ACTIONS(64), 1,
      sym_number,
    STATE(29), 1,
      sym_quoted_atom,
    STATE(15), 2,
      sym__prefix_operator,
      aux_sym_operator_expression_repeat1,
    STATE(38), 4,
      sym__primary,
      sym__symbol_operand,
      sym_compound,
      sym_group,
  [472] = 9,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_LPAREN2,
    ACTIONS(25), 1,
      sym_atom,
    ACTIONS(27), 1,
      sym_symbol,
    ACTIONS(31), 1,
      anon_sym_SQUOTE,
    ACTIONS(66), 1,
      sym_number,
    STATE(29), 1,
      sym_quoted_atom,
    STATE(32), 2,
      sym__prefix_operator,
      aux_sym_operator_expression_repeat1,
    STATE(37), 4,
      sym__primary,
      sym__symbol_operand,
      sym_compound,
      sym_group,
  [504] = 7,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(70), 1,
      anon_sym_LPAREN,
    ACTIONS(72), 1,
      anon_sym_LPAREN2,
    ACTIONS(74), 1,
      sym_atom,
    ACTIONS(77), 1,
      sym_symbol,
    ACTIONS(80), 2,
      sym_number,
      anon_sym_SQUOTE,
    ACTIONS(68), 5,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [531] = 7,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(70), 1,
      anon_sym_LPAREN,
    ACTIONS(72), 1,
      anon_sym_LPAREN2,
    ACTIONS(84), 1,
      sym_atom,
    ACTIONS(87), 1,
      sym_symbol,
    ACTIONS(80), 2,
      sym_number,
      anon_sym_SQUOTE,
    ACTIONS(82), 5,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [558] = 6,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(92), 1,
      sym_atom,
    ACTIONS(94), 1,
      sym_symbol,
    STATE(14), 1,
      sym__infix_operator,
    STATE(25), 1,
      aux_sym_operator_expression_repeat2,
    ACTIONS(90), 5,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [581] = 6,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(92), 1,
      sym_atom,
    ACTIONS(94), 1,
      sym_symbol,
    STATE(14), 1,
      sym__infix_operator,
    STATE(18), 1,
      aux_sym_operator_expression_repeat2,
    ACTIONS(96), 5,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [604] = 3,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(98), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(100), 7,
      sym_escape,
      anon_sym_AT_LBRACE,
      anon_sym_AT_LT,
      anon_sym_AT,
      anon_sym_AT_GT,
      anon_sym_AT_LBRACK,
      sym_block_close,
  [621] = 3,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(102), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(104), 7,
      sym_escape,
      anon_sym_AT_LBRACE,
      anon_sym_AT_LT,
      anon_sym_AT,
      anon_sym_AT_GT,
      anon_sym_AT_LBRACK,
      sym_block_close,
  [638] = 6,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(92), 1,
      sym_atom,
    ACTIONS(94), 1,
      sym_symbol,
    STATE(14), 1,
      sym__infix_operator,
    STATE(27), 1,
      aux_sym_operator_expression_repeat2,
    ACTIONS(90), 5,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [661] = 3,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(106), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(108), 7,
      sym_escape,
      anon_sym_AT_LBRACE,
      anon_sym_AT_LT,
      anon_sym_AT,
      anon_sym_AT_GT,
      anon_sym_AT_LBRACK,
      sym_block_close,
  [678] = 3,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(110), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(112), 7,
      sym_escape,
      anon_sym_AT_LBRACE,
      anon_sym_AT_LT,
      anon_sym_AT,
      anon_sym_AT_GT,
      anon_sym_AT_LBRACK,
      sym_block_close,
  [695] = 6,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(116), 1,
      sym_atom,
    ACTIONS(119), 1,
      sym_symbol,
    STATE(14), 1,
      sym__infix_operator,
    STATE(25), 1,
      aux_sym_operator_expression_repeat2,
    ACTIONS(114), 5,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [718] = 3,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(122), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(124), 7,
      sym_escape,
      anon_sym_AT_LBRACE,
      anon_sym_AT_LT,
      anon_sym_AT,
      anon_sym_AT_GT,
      anon_sym_AT_LBRACK,
      sym_block_close,
  [735] = 6,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(92), 1,
      sym_atom,
    ACTIONS(94), 1,
      sym_symbol,
    STATE(14), 1,
      sym__infix_operator,
    STATE(25), 1,
      aux_sym_operator_expression_repeat2,
    ACTIONS(126), 5,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [758] = 3,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(128), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(130), 7,
      sym_escape,
      anon_sym_AT_LBRACE,
      anon_sym_AT_LT,
      anon_sym_AT,
      anon_sym_AT_GT,
      anon_sym_AT_LBRACK,
      sym_block_close,
  [775] = 4,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(132), 1,
      anon_sym_LPAREN,
    ACTIONS(134), 1,
      sym_symbol,
    ACTIONS(68), 6,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_atom,
  [793] = 3,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(138), 1,
      sym_symbol,
    ACTIONS(136), 7,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_atom,
  [809] = 3,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(142), 1,
      sym_symbol,
    ACTIONS(140), 7,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_atom,
  [825] = 5,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(146), 1,
      sym_atom,
    ACTIONS(149), 1,
      sym_symbol,
    STATE(32), 2,
      sym__prefix_operator,
      aux_sym_operator_expression_repeat1,
    ACTIONS(144), 3,
      anon_sym_LPAREN2,
      sym_number,
      anon_sym_SQUOTE,
  [844] = 3,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(154), 1,
      sym_symbol,
    ACTIONS(152), 6,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_atom,
  [859] = 3,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(158), 1,
      sym_symbol,
    ACTIONS(156), 6,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_atom,
  [874] = 3,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(162), 1,
      sym_symbol,
    ACTIONS(160), 6,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_atom,
  [889] = 3,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(166), 1,
      sym_symbol,
    ACTIONS(164), 6,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_atom,
  [904] = 3,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(170), 1,
      sym_symbol,
    ACTIONS(168), 6,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_atom,
  [919] = 3,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(172), 1,
      sym_symbol,
    ACTIONS(114), 6,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_atom,
  [934] = 3,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(176), 1,
      sym_symbol,
    ACTIONS(174), 6,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_atom,
  [949] = 3,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(180), 1,
      sym_symbol,
    ACTIONS(178), 4,
      anon_sym_LPAREN2,
      sym_atom,
      sym_number,
      anon_sym_SQUOTE,
  [962] = 3,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(184), 1,
      sym_symbol,
    ACTIONS(182), 4,
      anon_sym_LPAREN2,
      sym_atom,
      sym_number,
      anon_sym_SQUOTE,
  [975] = 3,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(72), 1,
      sym_symbol,
    ACTIONS(80), 4,
      anon_sym_LPAREN2,
      sym_atom,
      sym_number,
      anon_sym_SQUOTE,
  [988] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 1,
      anon_sym_SEMI,
    STATE(47), 1,
      aux_sym__facts_repeat1,
    ACTIONS(186), 2,
      anon_sym_RBRACE,
      anon_sym_PIPE,
  [1002] = 4,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(192), 1,
      anon_sym_SQUOTE2,
    STATE(46), 1,
      aux_sym_quoted_atom_repeat1,
    ACTIONS(190), 2,
      aux_sym_quoted_atom_token1,
      sym_escape_sequence,
  [1016] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 1,
      anon_sym_SEMI,
    STATE(43), 1,
      aux_sym__facts_repeat1,
    ACTIONS(194), 2,
      anon_sym_RBRACE,
      anon_sym_PIPE,
  [1030] = 4,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(198), 1,
      anon_sym_SQUOTE2,
    STATE(48), 1,
      aux_sym_quoted_atom_repeat1,
    ACTIONS(196), 2,
      aux_sym_quoted_atom_token1,
      sym_escape_sequence,
  [1044] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(202), 1,
      anon_sym_SEMI,
    STATE(47), 1,
      aux_sym__facts_repeat1,
    ACTIONS(200), 2,
      anon_sym_RBRACE,
      anon_sym_PIPE,
  [1058] = 4,
    ACTIONS(21), 1,
      sym_comment,
    ACTIONS(208), 1,
      anon_sym_SQUOTE2,
    STATE(48), 1,
      aux_sym_quoted_atom_repeat1,
    ACTIONS(205), 2,
      aux_sym_quoted_atom_token1,
      sym_escape_sequence,
  [1072] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 1,
      anon_sym_COMMA,
    ACTIONS(213), 1,
      anon_sym_RPAREN,
    STATE(49), 1,
      aux_sym_compound_repeat1,
  [1085] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(215), 1,
      anon_sym_COMMA,
    ACTIONS(217), 1,
      anon_sym_RPAREN,
    STATE(52), 1,
      aux_sym_compound_repeat1,
  [1098] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(215), 1,
      anon_sym_COMMA,
    ACTIONS(219), 1,
      anon_sym_RPAREN,
    STATE(49), 1,
      aux_sym_compound_repeat1,
  [1111] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(215), 1,
      anon_sym_COMMA,
    ACTIONS(221), 1,
      anon_sym_RPAREN,
    STATE(49), 1,
      aux_sym_compound_repeat1,
  [1124] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(215), 1,
      anon_sym_COMMA,
    ACTIONS(223), 1,
      anon_sym_RPAREN,
    STATE(51), 1,
      aux_sym_compound_repeat1,
  [1137] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(200), 3,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_SEMI,
  [1146] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 2,
      anon_sym_LT,
      anon_sym_GT,
  [1154] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 1,
      anon_sym_LT,
    ACTIONS(229), 1,
      anon_sym_GT,
  [1164] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1172] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(233), 1,
      aux_sym__label_token1,
    STATE(56), 1,
      sym__label,
  [1182] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(235), 1,
      anon_sym_PIPE,
  [1189] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 1,
      ts_builtin_sym_end,
  [1196] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(239), 1,
      anon_sym_RBRACE,
  [1203] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(241), 1,
      anon_sym_PIPE,
  [1210] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 1,
      anon_sym_PIPE,
  [1217] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(245), 1,
      anon_sym_RPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 39,
  [SMALL_STATE(4)] = 78,
  [SMALL_STATE(5)] = 117,
  [SMALL_STATE(6)] = 156,
  [SMALL_STATE(7)] = 192,
  [SMALL_STATE(8)] = 228,
  [SMALL_STATE(9)] = 264,
  [SMALL_STATE(10)] = 300,
  [SMALL_STATE(11)] = 336,
  [SMALL_STATE(12)] = 372,
  [SMALL_STATE(13)] = 408,
  [SMALL_STATE(14)] = 440,
  [SMALL_STATE(15)] = 472,
  [SMALL_STATE(16)] = 504,
  [SMALL_STATE(17)] = 531,
  [SMALL_STATE(18)] = 558,
  [SMALL_STATE(19)] = 581,
  [SMALL_STATE(20)] = 604,
  [SMALL_STATE(21)] = 621,
  [SMALL_STATE(22)] = 638,
  [SMALL_STATE(23)] = 661,
  [SMALL_STATE(24)] = 678,
  [SMALL_STATE(25)] = 695,
  [SMALL_STATE(26)] = 718,
  [SMALL_STATE(27)] = 735,
  [SMALL_STATE(28)] = 758,
  [SMALL_STATE(29)] = 775,
  [SMALL_STATE(30)] = 793,
  [SMALL_STATE(31)] = 809,
  [SMALL_STATE(32)] = 825,
  [SMALL_STATE(33)] = 844,
  [SMALL_STATE(34)] = 859,
  [SMALL_STATE(35)] = 874,
  [SMALL_STATE(36)] = 889,
  [SMALL_STATE(37)] = 904,
  [SMALL_STATE(38)] = 919,
  [SMALL_STATE(39)] = 934,
  [SMALL_STATE(40)] = 949,
  [SMALL_STATE(41)] = 962,
  [SMALL_STATE(42)] = 975,
  [SMALL_STATE(43)] = 988,
  [SMALL_STATE(44)] = 1002,
  [SMALL_STATE(45)] = 1016,
  [SMALL_STATE(46)] = 1030,
  [SMALL_STATE(47)] = 1044,
  [SMALL_STATE(48)] = 1058,
  [SMALL_STATE(49)] = 1072,
  [SMALL_STATE(50)] = 1085,
  [SMALL_STATE(51)] = 1098,
  [SMALL_STATE(52)] = 1111,
  [SMALL_STATE(53)] = 1124,
  [SMALL_STATE(54)] = 1137,
  [SMALL_STATE(55)] = 1146,
  [SMALL_STATE(56)] = 1154,
  [SMALL_STATE(57)] = 1164,
  [SMALL_STATE(58)] = 1172,
  [SMALL_STATE(59)] = 1182,
  [SMALL_STATE(60)] = 1189,
  [SMALL_STATE(61)] = 1196,
  [SMALL_STATE(62)] = 1203,
  [SMALL_STATE(63)] = 1210,
  [SMALL_STATE(64)] = 1217,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [50] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [56] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [59] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__primary, 1, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__prefix_operator, 1, 0, 1),
  [74] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym__prefix_operator, 1, 0, 1), REDUCE(sym__primary, 1, 0, 0),
  [77] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym__prefix_operator, 1, 0, 1), REDUCE(sym__primary, 1, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__prefix_operator, 1, 0, 1),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__symbol_operand, 1, -1, 0),
  [84] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym__prefix_operator, 1, 0, 1), REDUCE(sym__symbol_operand, 1, -1, 0),
  [87] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym__prefix_operator, 1, 0, 1), REDUCE(sym__symbol_operand, 1, -1, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operator_expression, 2, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [94] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_region_open, 3, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_region_open, 3, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_region_close, 1, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_region_close, 1, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_region_close, 3, 0, 3),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_region_close, 3, 0, 3),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_open, 3, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_open, 3, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_operator_expression_repeat2, 2, 0, 0),
  [116] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_operator_expression_repeat2, 2, 0, 0), SHIFT_REPEAT(41),
  [119] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_operator_expression_repeat2, 2, 0, 0), SHIFT_REPEAT(40),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_region_open, 5, 0, 3),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_region_open, 5, 0, 3),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operator_expression, 3, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_point, 3, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_point, 3, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__primary, 1, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_atom, 3, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_atom, 3, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_atom, 2, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_atom, 2, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_operator_expression_repeat1, 2, 0, 0),
  [146] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_operator_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [149] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_operator_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group, 3, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_group, 3, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compound, 5, 0, 7),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_compound, 5, 0, 7),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compound, 4, 0, 5),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_compound, 4, 0, 5),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compound, 4, 0, 4),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_compound, 4, 0, 4),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_operator_expression_repeat2, 3, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_operator_expression_repeat2, 3, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_operator_expression_repeat2, 2, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compound, 5, 0, 9),
  [176] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_compound, 5, 0, 9),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__infix_operator, 1, 2, 1),
  [180] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__infix_operator, 1, 2, 1),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__infix_operator, 1, 1, 1),
  [184] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__infix_operator, 1, 1, 1),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__facts, 2, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [192] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__facts, 1, 0, 0),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [198] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__facts_repeat1, 2, 0, 0),
  [202] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__facts_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [205] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quoted_atom_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [208] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quoted_atom_repeat1, 2, 0, 0),
  [210] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_compound_repeat1, 2, 0, 8), SHIFT_REPEAT(11),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_compound_repeat1, 2, 0, 8),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__label, 1, 0, 2),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_compound_repeat1, 2, 0, 6),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [237] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_ilk(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "ilk",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
