/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 48
#define LARGE_STATE_COUNT 9
#define SYMBOL_COUNT 29
#define ALIAS_COUNT 2
#define TOKEN_COUNT 14
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 8
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_SEMI = 1,
  anon_sym_LPAREN = 2,
  anon_sym_COMMA = 3,
  anon_sym_RPAREN = 4,
  anon_sym_LPAREN2 = 5,
  sym_atom = 6,
  sym_symbol = 7,
  sym_number = 8,
  anon_sym_SQUOTE = 9,
  aux_sym_quoted_atom_token1 = 10,
  anon_sym_SQUOTE2 = 11,
  sym_escape_sequence = 12,
  sym_comment = 13,
  sym_source_file = 14,
  sym__expression = 15,
  sym_operator_expression = 16,
  sym__prefix_operator = 17,
  sym__infix_operator = 18,
  sym__primary = 19,
  sym__symbol_operand = 20,
  sym_compound = 21,
  sym_group = 22,
  sym_quoted_atom = 23,
  aux_sym_source_file_repeat1 = 24,
  aux_sym_operator_expression_repeat1 = 25,
  aux_sym_operator_expression_repeat2 = 26,
  aux_sym_compound_repeat1 = 27,
  aux_sym_quoted_atom_repeat1 = 28,
  alias_sym_functor = 29,
  alias_sym_operator = 30,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SEMI] = ";",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LPAREN2] = "(",
  [sym_atom] = "atom",
  [sym_symbol] = "symbol",
  [sym_number] = "number",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_quoted_atom_token1] = "quoted_atom_token1",
  [anon_sym_SQUOTE2] = "'",
  [sym_escape_sequence] = "escape_sequence",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym__expression] = "_expression",
  [sym_operator_expression] = "operator_expression",
  [sym__prefix_operator] = "_prefix_operator",
  [sym__infix_operator] = "_infix_operator",
  [sym__primary] = "_primary",
  [sym__symbol_operand] = "_symbol_operand",
  [sym_compound] = "compound",
  [sym_group] = "group",
  [sym_quoted_atom] = "quoted_atom",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_operator_expression_repeat1] = "operator_expression_repeat1",
  [aux_sym_operator_expression_repeat2] = "operator_expression_repeat2",
  [aux_sym_compound_repeat1] = "compound_repeat1",
  [aux_sym_quoted_atom_repeat1] = "quoted_atom_repeat1",
  [alias_sym_functor] = "functor",
  [alias_sym_operator] = "operator",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LPAREN2] = anon_sym_LPAREN,
  [sym_atom] = sym_atom,
  [sym_symbol] = sym_symbol,
  [sym_number] = sym_number,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_quoted_atom_token1] = aux_sym_quoted_atom_token1,
  [anon_sym_SQUOTE2] = anon_sym_SQUOTE,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym__expression] = sym__expression,
  [sym_operator_expression] = sym_operator_expression,
  [sym__prefix_operator] = sym__prefix_operator,
  [sym__infix_operator] = sym__infix_operator,
  [sym__primary] = sym__primary,
  [sym__symbol_operand] = sym__symbol_operand,
  [sym_compound] = sym_compound,
  [sym_group] = sym_group,
  [sym_quoted_atom] = sym_quoted_atom,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_operator_expression_repeat1] = aux_sym_operator_expression_repeat1,
  [aux_sym_operator_expression_repeat2] = aux_sym_operator_expression_repeat2,
  [aux_sym_compound_repeat1] = aux_sym_compound_repeat1,
  [aux_sym_quoted_atom_repeat1] = aux_sym_quoted_atom_repeat1,
  [alias_sym_functor] = alias_sym_functor,
  [alias_sym_operator] = alias_sym_operator,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN2] = {
    .visible = true,
    .named = false,
  },
  [sym_atom] = {
    .visible = true,
    .named = true,
  },
  [sym_symbol] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_atom_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE2] = {
    .visible = true,
    .named = false,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_operator_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__prefix_operator] = {
    .visible = false,
    .named = true,
  },
  [sym__infix_operator] = {
    .visible = false,
    .named = true,
  },
  [sym__primary] = {
    .visible = false,
    .named = true,
  },
  [sym__symbol_operand] = {
    .visible = false,
    .named = true,
  },
  [sym_compound] = {
    .visible = true,
    .named = true,
  },
  [sym_group] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_atom] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_operator_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_operator_expression_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_compound_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quoted_atom_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_functor] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_operator] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_argument = 1,
  field_functor = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_argument] = "argument",
  [field_functor] = "functor",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [2] = {.index = 0, .length = 2},
  [3] = {.index = 0, .length = 2},
  [4] = {.index = 2, .length = 1},
  [5] = {.index = 3, .length = 3},
  [6] = {.index = 6, .length = 2},
  [7] = {.index = 3, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_argument, 2},
    {field_functor, 0},
  [2] =
    {field_argument, 1},
  [3] =
    {field_argument, 2},
    {field_argument, 3, .inherited = true},
    {field_functor, 0},
  [6] =
    {field_argument, 0, .inherited = true},
    {field_argument, 1, .inherited = true},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = alias_sym_operator,
  },
  [2] = {
    [0] = alias_sym_functor,
  },
  [5] = {
    [0] = alias_sym_functor,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
};

static const TSCharacterRange sym_symbol_character_set_1[] = {
  {'&', '&'}, {'*', '+'}, {'-', '/'}, {':', ':'}, {'<', '>'}, {'@', '@'}, {'\\', '\\'}, {'^', '^'},
  {'~', '~'},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(25);
      ADVANCE_MAP(
        '\'', 48,
        '(', 27,
        ')', 29,
        ',', 28,
        '-', 37,
        '/', 34,
        ';', 26,
        '#', 33,
        '$', 33,
        '?', 33,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(20);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      if (('&' <= lookahead && lookahead <= '@') ||
          lookahead == '\\' ||
          lookahead == '^' ||
          lookahead == '~') ADVANCE(38);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 1:
      if (lookahead == ' ') ADVANCE(43);
      if (lookahead == '\'') ADVANCE(49);
      if (lookahead == '/') ADVANCE(46);
      if (lookahead == '\\') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(5);
      if (lookahead > ' ' &&
          lookahead != 0x7f &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(47);
      END_STATE();
    case 2:
      if (lookahead == '*') ADVANCE(4);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(3);
      if (lookahead == '/') ADVANCE(51);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(4);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(3);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '/') ADVANCE(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      END_STATE();
    case 6:
      if (lookahead == 'U') ADVANCE(17);
      if (lookahead == 'u') ADVANCE(13);
      if (lookahead == '\'' ||
          lookahead == '\\' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't') ADVANCE(50);
      END_STATE();
    case 7:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      END_STATE();
    case 8:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      END_STATE();
    case 9:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      END_STATE();
    case 10:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(50);
      END_STATE();
    case 11:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(10);
      END_STATE();
    case 12:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(11);
      END_STATE();
    case 13:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(12);
      END_STATE();
    case 14:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(13);
      END_STATE();
    case 15:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(14);
      END_STATE();
    case 16:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(15);
      END_STATE();
    case 17:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(16);
      END_STATE();
    case 18:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 19:
      if (eof) ADVANCE(25);
      ADVANCE_MAP(
        '\'', 42,
        '(', 27,
        ')', 29,
        ',', 28,
        '-', 37,
        '/', 34,
        ';', 26,
        '#', 33,
        '$', 33,
        '?', 33,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(20);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      if (('&' <= lookahead && lookahead <= '@') ||
          lookahead == '\\' ||
          lookahead == '^' ||
          lookahead == '~') ADVANCE(38);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 20:
      if (eof) ADVANCE(25);
      ADVANCE_MAP(
        '\'', 42,
        '(', 30,
        ')', 29,
        ',', 28,
        '-', 37,
        '/', 34,
        ';', 26,
        '#', 33,
        '$', 33,
        '?', 33,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(20);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      if (('&' <= lookahead && lookahead <= '@') ||
          lookahead == '\\' ||
          lookahead == '^' ||
          lookahead == '~') ADVANCE(38);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 21:
      if (eof) ADVANCE(25);
      if (lookahead == '\'') ADVANCE(42);
      if (lookahead == '(') ADVANCE(30);
      if (lookahead == '-') ADVANCE(37);
      if (lookahead == '/') ADVANCE(34);
      if (lookahead == '#' ||
          lookahead == '$' ||
          lookahead == '?') ADVANCE(33);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(21);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      if (lookahead == '&' ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('.' <= lookahead && lookahead <= ':') ||
          ('<' <= lookahead && lookahead <= '@') ||
          lookahead == '\\' ||
          lookahead == '^' ||
          lookahead == '~') ADVANCE(38);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 22:
      if (eof) ADVANCE(25);
      if (lookahead == '(') ADVANCE(27);
      if (lookahead == ')') ADVANCE(29);
      if (lookahead == ',') ADVANCE(28);
      if (lookahead == '/') ADVANCE(34);
      if (lookahead == ';') ADVANCE(26);
      if (lookahead == '#' ||
          lookahead == '$' ||
          lookahead == '?') ADVANCE(33);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(23);
      if (lookahead == '&' ||
          ('*' <= lookahead && lookahead <= '.') ||
          (':' <= lookahead && lookahead <= '@') ||
          lookahead == '\\' ||
          lookahead == '^' ||
          lookahead == '~') ADVANCE(38);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 23:
      if (eof) ADVANCE(25);
      if (lookahead == ')') ADVANCE(29);
      if (lookahead == ',') ADVANCE(28);
      if (lookahead == '/') ADVANCE(34);
      if (lookahead == ';') ADVANCE(26);
      if (lookahead == '#' ||
          lookahead == '$' ||
          lookahead == '?') ADVANCE(33);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(23);
      if (lookahead == '&' ||
          ('*' <= lookahead && lookahead <= '.') ||
          (':' <= lookahead && lookahead <= '@') ||
          lookahead == '\\' ||
          lookahead == '^' ||
          lookahead == '~') ADVANCE(38);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 24:
      if (eof) ADVANCE(25);
      if (lookahead == ')') ADVANCE(29);
      if (lookahead == ',') ADVANCE(28);
      if (lookahead == '/') ADVANCE(2);
      if (lookahead == ';') ADVANCE(26);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_LPAREN2);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_atom);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == '_') ADVANCE(18);
      if (lookahead == '#' ||
          lookahead == '$' ||
          lookahead == '?') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_atom);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == '*') ADVANCE(36);
      if (set_contains(sym_symbol_character_set_1, 9, lookahead)) ADVANCE(38);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == '*') ADVANCE(35);
      if (lookahead == '/') ADVANCE(38);
      if (set_contains(sym_symbol_character_set_1, 9, lookahead)) ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(4);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == '*') ADVANCE(35);
      if (set_contains(sym_symbol_character_set_1, 9, lookahead)) ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(4);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_symbol);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      if (set_contains(sym_symbol_character_set_1, 9, lookahead)) ADVANCE(38);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_symbol);
      if (set_contains(sym_symbol_character_set_1, 9, lookahead)) ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(8);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_quoted_atom_token1);
      if (lookahead == ' ') ADVANCE(43);
      if (lookahead == '/') ADVANCE(46);
      if (lookahead > ' ' &&
          lookahead != '\'' &&
          lookahead != '\\' &&
          lookahead != 0x7f &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(47);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_quoted_atom_token1);
      if (lookahead == '*') ADVANCE(44);
      if (lookahead == '/') ADVANCE(47);
      if (lookahead > 0x1f &&
          lookahead != '\'' &&
          lookahead != '\\' &&
          lookahead != 0x7f &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(45);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_quoted_atom_token1);
      if (lookahead == '*') ADVANCE(44);
      if (lookahead > 0x1f &&
          lookahead != '\'' &&
          lookahead != '\\' &&
          lookahead != 0x7f &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_quoted_atom_token1);
      if (lookahead == '*') ADVANCE(45);
      if (lookahead > 0x1f &&
          lookahead != '\'' &&
          lookahead != '\\' &&
          lookahead != 0x7f &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(47);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_quoted_atom_token1);
      if (lookahead > 0x1f &&
          lookahead != '\'' &&
          lookahead != '\\' &&
          lookahead != 0x7f &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_SQUOTE2);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_SQUOTE2);
      if (lookahead == '\'') ADVANCE(50);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 21},
  [2] = {.lex_state = 21},
  [3] = {.lex_state = 21},
  [4] = {.lex_state = 21},
  [5] = {.lex_state = 21},
  [6] = {.lex_state = 21},
  [7] = {.lex_state = 21},
  [8] = {.lex_state = 21},
  [9] = {.lex_state = 21},
  [10] = {.lex_state = 21},
  [11] = {.lex_state = 21},
  [12] = {.lex_state = 19},
  [13] = {.lex_state = 19},
  [14] = {.lex_state = 22},
  [15] = {.lex_state = 22},
  [16] = {.lex_state = 22},
  [17] = {.lex_state = 22},
  [18] = {.lex_state = 22},
  [19] = {.lex_state = 22},
  [20] = {.lex_state = 22},
  [21] = {.lex_state = 21},
  [22] = {.lex_state = 22},
  [23] = {.lex_state = 22},
  [24] = {.lex_state = 22},
  [25] = {.lex_state = 22},
  [26] = {.lex_state = 22},
  [27] = {.lex_state = 22},
  [28] = {.lex_state = 22},
  [29] = {.lex_state = 22},
  [30] = {.lex_state = 21},
  [31] = {.lex_state = 21},
  [32] = {.lex_state = 21},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 24},
  [37] = {.lex_state = 24},
  [38] = {.lex_state = 24},
  [39] = {.lex_state = 24},
  [40] = {.lex_state = 24},
  [41] = {.lex_state = 24},
  [42] = {.lex_state = 24},
  [43] = {.lex_state = 24},
  [44] = {.lex_state = 24},
  [45] = {.lex_state = 24},
  [46] = {.lex_state = 24},
  [47] = {.lex_state = 24},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LPAREN2] = ACTIONS(1),
    [sym_atom] = ACTIONS(1),
    [sym_symbol] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE2] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(47),
    [sym__expression] = STATE(42),
    [sym_operator_expression] = STATE(42),
    [sym__prefix_operator] = STATE(9),
    [sym__primary] = STATE(14),
    [sym__symbol_operand] = STATE(14),
    [sym_compound] = STATE(14),
    [sym_group] = STATE(14),
    [sym_quoted_atom] = STATE(19),
    [aux_sym_operator_expression_repeat1] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_LPAREN2] = ACTIONS(7),
    [sym_atom] = ACTIONS(9),
    [sym_symbol] = ACTIONS(11),
    [sym_number] = ACTIONS(13),
    [anon_sym_SQUOTE] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(2)] = {
    [sym__expression] = STATE(44),
    [sym_operator_expression] = STATE(44),
    [sym__prefix_operator] = STATE(9),
    [sym__primary] = STATE(14),
    [sym__symbol_operand] = STATE(14),
    [sym_compound] = STATE(14),
    [sym_group] = STATE(14),
    [sym_quoted_atom] = STATE(19),
    [aux_sym_operator_expression_repeat1] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(17),
    [anon_sym_LPAREN2] = ACTIONS(7),
    [sym_atom] = ACTIONS(9),
    [sym_symbol] = ACTIONS(11),
    [sym_number] = ACTIONS(13),
    [anon_sym_SQUOTE] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(3)] = {
    [sym__expression] = STATE(44),
    [sym_operator_expression] = STATE(44),
    [sym__prefix_operator] = STATE(9),
    [sym__primary] = STATE(14),
    [sym__symbol_operand] = STATE(14),
    [sym_compound] = STATE(14),
    [sym_group] = STATE(14),
    [sym_quoted_atom] = STATE(19),
    [aux_sym_operator_expression_repeat1] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(19),
    [anon_sym_LPAREN2] = ACTIONS(7),
    [sym_atom] = ACTIONS(9),
    [sym_symbol] = ACTIONS(11),
    [sym_number] = ACTIONS(13),
    [anon_sym_SQUOTE] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(4)] = {
    [sym__expression] = STATE(46),
    [sym_operator_expression] = STATE(46),
    [sym__prefix_operator] = STATE(9),
    [sym__primary] = STATE(14),
    [sym__symbol_operand] = STATE(14),
    [sym_compound] = STATE(14),
    [sym_group] = STATE(14),
    [sym_quoted_atom] = STATE(19),
    [aux_sym_operator_expression_repeat1] = STATE(9),
    [anon_sym_LPAREN2] = ACTIONS(7),
    [sym_atom] = ACTIONS(9),
    [sym_symbol] = ACTIONS(11),
    [sym_number] = ACTIONS(13),
    [anon_sym_SQUOTE] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(5)] = {
    [sym__expression] = STATE(38),
    [sym_operator_expression] = STATE(38),
    [sym__prefix_operator] = STATE(9),
    [sym__primary] = STATE(14),
    [sym__symbol_operand] = STATE(14),
    [sym_compound] = STATE(14),
    [sym_group] = STATE(14),
    [sym_quoted_atom] = STATE(19),
    [aux_sym_operator_expression_repeat1] = STATE(9),
    [anon_sym_LPAREN2] = ACTIONS(7),
    [sym_atom] = ACTIONS(9),
    [sym_symbol] = ACTIONS(11),
    [sym_number] = ACTIONS(13),
    [anon_sym_SQUOTE] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(6)] = {
    [sym__expression] = STATE(39),
    [sym_operator_expression] = STATE(39),
    [sym__prefix_operator] = STATE(9),
    [sym__primary] = STATE(14),
    [sym__symbol_operand] = STATE(14),
    [sym_compound] = STATE(14),
    [sym_group] = STATE(14),
    [sym_quoted_atom] = STATE(19),
    [aux_sym_operator_expression_repeat1] = STATE(9),
    [anon_sym_LPAREN2] = ACTIONS(7),
    [sym_atom] = ACTIONS(9),
    [sym_symbol] = ACTIONS(11),
    [sym_number] = ACTIONS(13),
    [anon_sym_SQUOTE] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(7)] = {
    [sym__expression] = STATE(45),
    [sym_operator_expression] = STATE(45),
    [sym__prefix_operator] = STATE(9),
    [sym__primary] = STATE(14),
    [sym__symbol_operand] = STATE(14),
    [sym_compound] = STATE(14),
    [sym_group] = STATE(14),
    [sym_quoted_atom] = STATE(19),
    [aux_sym_operator_expression_repeat1] = STATE(9),
    [anon_sym_LPAREN2] = ACTIONS(7),
    [sym_atom] = ACTIONS(9),
    [sym_symbol] = ACTIONS(11),
    [sym_number] = ACTIONS(13),
    [anon_sym_SQUOTE] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(8)] = {
    [sym__expression] = STATE(44),
    [sym_operator_expression] = STATE(44),
    [sym__prefix_operator] = STATE(9),
    [sym__primary] = STATE(14),
    [sym__symbol_operand] = STATE(14),
    [sym_compound] = STATE(14),
    [sym_group] = STATE(14),
    [sym_quoted_atom] = STATE(19),
    [aux_sym_operator_expression_repeat1] = STATE(9),
    [anon_sym_LPAREN2] = ACTIONS(7),
    [sym_atom] = ACTIONS(9),
    [sym_symbol] = ACTIONS(11),
    [sym_number] = ACTIONS(13),
    [anon_sym_SQUOTE] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LPAREN2,
    ACTIONS(9), 1,
      sym_atom,
    ACTIONS(11), 1,
      sym_symbol,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(21), 1,
      sym_number,
    STATE(19), 1,
      sym_quoted_atom,
    STATE(21), 2,
      sym__prefix_operator,
      aux_sym_operator_expression_repeat1,
    STATE(15), 4,
      sym__primary,
      sym__symbol_operand,
      sym_compound,
      sym_group,
  [32] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LPAREN2,
    ACTIONS(9), 1,
      sym_atom,
    ACTIONS(11), 1,
      sym_symbol,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      sym_number,
    STATE(19), 1,
      sym_quoted_atom,
    STATE(11), 2,
      sym__prefix_operator,
      aux_sym_operator_expression_repeat1,
    STATE(25), 4,
      sym__primary,
      sym__symbol_operand,
      sym_compound,
      sym_group,
  [64] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LPAREN2,
    ACTIONS(9), 1,
      sym_atom,
    ACTIONS(11), 1,
      sym_symbol,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(25), 1,
      sym_number,
    STATE(19), 1,
      sym_quoted_atom,
    STATE(21), 2,
      sym__prefix_operator,
      aux_sym_operator_expression_repeat1,
    STATE(27), 4,
      sym__primary,
      sym__symbol_operand,
      sym_compound,
      sym_group,
  [96] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_LPAREN2,
    ACTIONS(33), 1,
      sym_atom,
    ACTIONS(36), 1,
      sym_symbol,
    ACTIONS(39), 2,
      sym_number,
      anon_sym_SQUOTE,
    ACTIONS(27), 4,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [122] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_LPAREN2,
    ACTIONS(43), 1,
      sym_atom,
    ACTIONS(46), 1,
      sym_symbol,
    ACTIONS(39), 2,
      sym_number,
      anon_sym_SQUOTE,
    ACTIONS(41), 4,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [148] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(51), 1,
      sym_atom,
    ACTIONS(53), 1,
      sym_symbol,
    STATE(10), 1,
      sym__infix_operator,
    STATE(16), 1,
      aux_sym_operator_expression_repeat2,
    ACTIONS(49), 4,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [170] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(51), 1,
      sym_atom,
    ACTIONS(53), 1,
      sym_symbol,
    STATE(10), 1,
      sym__infix_operator,
    STATE(17), 1,
      aux_sym_operator_expression_repeat2,
    ACTIONS(55), 4,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [192] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(51), 1,
      sym_atom,
    ACTIONS(53), 1,
      sym_symbol,
    STATE(10), 1,
      sym__infix_operator,
    STATE(18), 1,
      aux_sym_operator_expression_repeat2,
    ACTIONS(55), 4,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [214] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(51), 1,
      sym_atom,
    ACTIONS(53), 1,
      sym_symbol,
    STATE(10), 1,
      sym__infix_operator,
    STATE(18), 1,
      aux_sym_operator_expression_repeat2,
    ACTIONS(57), 4,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [236] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(61), 1,
      sym_atom,
    ACTIONS(64), 1,
      sym_symbol,
    STATE(10), 1,
      sym__infix_operator,
    STATE(18), 1,
      aux_sym_operator_expression_repeat2,
    ACTIONS(59), 4,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [258] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 1,
      anon_sym_LPAREN,
    ACTIONS(69), 1,
      sym_symbol,
    ACTIONS(27), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_atom,
  [275] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 1,
      sym_symbol,
    ACTIONS(71), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_atom,
  [290] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 1,
      sym_atom,
    ACTIONS(80), 1,
      sym_symbol,
    STATE(21), 2,
      sym__prefix_operator,
      aux_sym_operator_expression_repeat1,
    ACTIONS(75), 3,
      anon_sym_LPAREN2,
      sym_number,
      anon_sym_SQUOTE,
  [309] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      sym_symbol,
    ACTIONS(83), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_atom,
  [324] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 1,
      sym_symbol,
    ACTIONS(87), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_atom,
  [338] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      sym_symbol,
    ACTIONS(91), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_atom,
  [352] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      sym_symbol,
    ACTIONS(59), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_atom,
  [366] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 1,
      sym_symbol,
    ACTIONS(97), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_atom,
  [380] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 1,
      sym_symbol,
    ACTIONS(101), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_atom,
  [394] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 1,
      sym_symbol,
    ACTIONS(105), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_atom,
  [408] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 1,
      sym_symbol,
    ACTIONS(109), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_atom,
  [422] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      sym_symbol,
    ACTIONS(113), 4,
      anon_sym_LPAREN2,
      sym_atom,
      sym_number,
      anon_sym_SQUOTE,
  [435] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 1,
      sym_symbol,
    ACTIONS(117), 4,
      anon_sym_LPAREN2,
      sym_atom,
      sym_number,
      anon_sym_SQUOTE,
  [448] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(31), 1,
      sym_symbol,
    ACTIONS(39), 4,
      anon_sym_LPAREN2,
      sym_atom,
      sym_number,
      anon_sym_SQUOTE,
  [461] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(124), 1,
      anon_sym_SQUOTE2,
    STATE(33), 1,
      aux_sym_quoted_atom_repeat1,
    ACTIONS(121), 2,
      aux_sym_quoted_atom_token1,
      sym_escape_sequence,
  [475] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(128), 1,
      anon_sym_SQUOTE2,
    STATE(35), 1,
      aux_sym_quoted_atom_repeat1,
    ACTIONS(126), 2,
      aux_sym_quoted_atom_token1,
      sym_escape_sequence,
  [489] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 1,
      anon_sym_SQUOTE2,
    STATE(33), 1,
      aux_sym_quoted_atom_repeat1,
    ACTIONS(130), 2,
      aux_sym_quoted_atom_token1,
      sym_escape_sequence,
  [503] = 4,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    ACTIONS(134), 1,
      anon_sym_SEMI,
    ACTIONS(136), 1,
      sym_comment,
    STATE(37), 1,
      aux_sym_source_file_repeat1,
  [516] = 4,
    ACTIONS(136), 1,
      sym_comment,
    ACTIONS(138), 1,
      ts_builtin_sym_end,
    ACTIONS(140), 1,
      anon_sym_SEMI,
    STATE(37), 1,
      aux_sym_source_file_repeat1,
  [529] = 4,
    ACTIONS(136), 1,
      sym_comment,
    ACTIONS(143), 1,
      anon_sym_COMMA,
    ACTIONS(145), 1,
      anon_sym_RPAREN,
    STATE(41), 1,
      aux_sym_compound_repeat1,
  [542] = 4,
    ACTIONS(136), 1,
      sym_comment,
    ACTIONS(143), 1,
      anon_sym_COMMA,
    ACTIONS(147), 1,
      anon_sym_RPAREN,
    STATE(40), 1,
      aux_sym_compound_repeat1,
  [555] = 4,
    ACTIONS(136), 1,
      sym_comment,
    ACTIONS(143), 1,
      anon_sym_COMMA,
    ACTIONS(149), 1,
      anon_sym_RPAREN,
    STATE(43), 1,
      aux_sym_compound_repeat1,
  [568] = 4,
    ACTIONS(136), 1,
      sym_comment,
    ACTIONS(143), 1,
      anon_sym_COMMA,
    ACTIONS(151), 1,
      anon_sym_RPAREN,
    STATE(43), 1,
      aux_sym_compound_repeat1,
  [581] = 4,
    ACTIONS(136), 1,
      sym_comment,
    ACTIONS(153), 1,
      ts_builtin_sym_end,
    ACTIONS(155), 1,
      anon_sym_SEMI,
    STATE(36), 1,
      aux_sym_source_file_repeat1,
  [594] = 4,
    ACTIONS(136), 1,
      sym_comment,
    ACTIONS(157), 1,
      anon_sym_COMMA,
    ACTIONS(160), 1,
      anon_sym_RPAREN,
    STATE(43), 1,
      aux_sym_compound_repeat1,
  [607] = 2,
    ACTIONS(136), 1,
      sym_comment,
    ACTIONS(138), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
  [615] = 2,
    ACTIONS(136), 1,
      sym_comment,
    ACTIONS(162), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [623] = 2,
    ACTIONS(136), 1,
      sym_comment,
    ACTIONS(164), 1,
      anon_sym_RPAREN,
  [630] = 2,
    ACTIONS(136), 1,
      sym_comment,
    ACTIONS(166), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(9)] = 0,
  [SMALL_STATE(10)] = 32,
  [SMALL_STATE(11)] = 64,
  [SMALL_STATE(12)] = 96,
  [SMALL_STATE(13)] = 122,
  [SMALL_STATE(14)] = 148,
  [SMALL_STATE(15)] = 170,
  [SMALL_STATE(16)] = 192,
  [SMALL_STATE(17)] = 214,
  [SMALL_STATE(18)] = 236,
  [SMALL_STATE(19)] = 258,
  [SMALL_STATE(20)] = 275,
  [SMALL_STATE(21)] = 290,
  [SMALL_STATE(22)] = 309,
  [SMALL_STATE(23)] = 324,
  [SMALL_STATE(24)] = 338,
  [SMALL_STATE(25)] = 352,
  [SMALL_STATE(26)] = 366,
  [SMALL_STATE(27)] = 380,
  [SMALL_STATE(28)] = 394,
  [SMALL_STATE(29)] = 408,
  [SMALL_STATE(30)] = 422,
  [SMALL_STATE(31)] = 435,
  [SMALL_STATE(32)] = 448,
  [SMALL_STATE(33)] = 461,
  [SMALL_STATE(34)] = 475,
  [SMALL_STATE(35)] = 489,
  [SMALL_STATE(36)] = 503,
  [SMALL_STATE(37)] = 516,
  [SMALL_STATE(38)] = 529,
  [SMALL_STATE(39)] = 542,
  [SMALL_STATE(40)] = 555,
  [SMALL_STATE(41)] = 568,
  [SMALL_STATE(42)] = 581,
  [SMALL_STATE(43)] = 594,
  [SMALL_STATE(44)] = 607,
  [SMALL_STATE(45)] = 615,
  [SMALL_STATE(46)] = 623,
  [SMALL_STATE(47)] = 630,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__primary, 1, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [31] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__prefix_operator, 1, 0, 1),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym__prefix_operator, 1, 0, 1), REDUCE(sym__primary, 1, 0, 0),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym__prefix_operator, 1, 0, 1), REDUCE(sym__primary, 1, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__prefix_operator, 1, 0, 1),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__symbol_operand, 1, -1, 0),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym__prefix_operator, 1, 0, 1), REDUCE(sym__symbol_operand, 1, -1, 0),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym__prefix_operator, 1, 0, 1), REDUCE(sym__symbol_operand, 1, -1, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operator_expression, 2, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operator_expression, 3, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_operator_expression_repeat2, 2, 0, 0),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_operator_expression_repeat2, 2, 0, 0), SHIFT_REPEAT(30),
  [64] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_operator_expression_repeat2, 2, 0, 0), SHIFT_REPEAT(31),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__primary, 1, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_atom, 2, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_atom, 2, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_operator_expression_repeat1, 2, 0, 0),
  [77] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_operator_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [80] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_operator_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_atom, 3, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_atom, 3, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compound, 4, 0, 3),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_compound, 4, 0, 3),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group, 3, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_group, 3, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_operator_expression_repeat2, 2, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compound, 4, 0, 2),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_compound, 4, 0, 2),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_operator_expression_repeat2, 3, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_operator_expression_repeat2, 3, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compound, 5, 0, 5),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_compound, 5, 0, 5),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compound, 5, 0, 7),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_compound, 5, 0, 7),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__infix_operator, 1, 1, 1),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__infix_operator, 1, 1, 1),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__infix_operator, 1, 2, 1),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__infix_operator, 1, 2, 1),
  [121] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quoted_atom_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quoted_atom_repeat1, 2, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [128] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [132] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [140] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [157] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_compound_repeat1, 2, 0, 6), SHIFT_REPEAT(7),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_compound_repeat1, 2, 0, 6),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_compound_repeat1, 2, 0, 4),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [166] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_ilk_meta(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "ilk_meta",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
