/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 57
#define LARGE_STATE_COUNT 11
#define SYMBOL_COUNT 33
#define ALIAS_COUNT 2
#define TOKEN_COUNT 16
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 11
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_SEMI = 1,
  anon_sym_LPAREN = 2,
  anon_sym_COMMA = 3,
  anon_sym_RPAREN = 4,
  anon_sym_LBRACK = 5,
  anon_sym_RBRACK = 6,
  anon_sym_LPAREN2 = 7,
  sym_atom = 8,
  sym_symbol = 9,
  sym_number = 10,
  anon_sym_SQUOTE = 11,
  aux_sym_quoted_atom_token1 = 12,
  anon_sym_SQUOTE2 = 13,
  sym_escape_sequence = 14,
  sym_comment = 15,
  sym_source_file = 16,
  sym__expression = 17,
  sym_operator_expression = 18,
  sym__prefix_operator = 19,
  sym__infix_operator = 20,
  sym__primary = 21,
  sym__symbol_operand = 22,
  sym_compound = 23,
  sym_sequence = 24,
  sym_group = 25,
  sym_quoted_atom = 26,
  aux_sym_source_file_repeat1 = 27,
  aux_sym_operator_expression_repeat1 = 28,
  aux_sym_operator_expression_repeat2 = 29,
  aux_sym_compound_repeat1 = 30,
  aux_sym_sequence_repeat1 = 31,
  aux_sym_quoted_atom_repeat1 = 32,
  alias_sym_functor = 33,
  alias_sym_operator = 34,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SEMI] = ";",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LPAREN2] = "(",
  [sym_atom] = "atom",
  [sym_symbol] = "symbol",
  [sym_number] = "number",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_quoted_atom_token1] = "quoted_atom_token1",
  [anon_sym_SQUOTE2] = "'",
  [sym_escape_sequence] = "escape_sequence",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym__expression] = "_expression",
  [sym_operator_expression] = "operator_expression",
  [sym__prefix_operator] = "_prefix_operator",
  [sym__infix_operator] = "_infix_operator",
  [sym__primary] = "_primary",
  [sym__symbol_operand] = "_symbol_operand",
  [sym_compound] = "compound",
  [sym_sequence] = "sequence",
  [sym_group] = "group",
  [sym_quoted_atom] = "quoted_atom",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_operator_expression_repeat1] = "operator_expression_repeat1",
  [aux_sym_operator_expression_repeat2] = "operator_expression_repeat2",
  [aux_sym_compound_repeat1] = "compound_repeat1",
  [aux_sym_sequence_repeat1] = "sequence_repeat1",
  [aux_sym_quoted_atom_repeat1] = "quoted_atom_repeat1",
  [alias_sym_functor] = "functor",
  [alias_sym_operator] = "operator",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LPAREN2] = anon_sym_LPAREN,
  [sym_atom] = sym_atom,
  [sym_symbol] = sym_symbol,
  [sym_number] = sym_number,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_quoted_atom_token1] = aux_sym_quoted_atom_token1,
  [anon_sym_SQUOTE2] = anon_sym_SQUOTE,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym__expression] = sym__expression,
  [sym_operator_expression] = sym_operator_expression,
  [sym__prefix_operator] = sym__prefix_operator,
  [sym__infix_operator] = sym__infix_operator,
  [sym__primary] = sym__primary,
  [sym__symbol_operand] = sym__symbol_operand,
  [sym_compound] = sym_compound,
  [sym_sequence] = sym_sequence,
  [sym_group] = sym_group,
  [sym_quoted_atom] = sym_quoted_atom,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_operator_expression_repeat1] = aux_sym_operator_expression_repeat1,
  [aux_sym_operator_expression_repeat2] = aux_sym_operator_expression_repeat2,
  [aux_sym_compound_repeat1] = aux_sym_compound_repeat1,
  [aux_sym_sequence_repeat1] = aux_sym_sequence_repeat1,
  [aux_sym_quoted_atom_repeat1] = aux_sym_quoted_atom_repeat1,
  [alias_sym_functor] = alias_sym_functor,
  [alias_sym_operator] = alias_sym_operator,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN2] = {
    .visible = true,
    .named = false,
  },
  [sym_atom] = {
    .visible = true,
    .named = true,
  },
  [sym_symbol] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_atom_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE2] = {
    .visible = true,
    .named = false,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_operator_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__prefix_operator] = {
    .visible = false,
    .named = true,
  },
  [sym__infix_operator] = {
    .visible = false,
    .named = true,
  },
  [sym__primary] = {
    .visible = false,
    .named = true,
  },
  [sym__symbol_operand] = {
    .visible = false,
    .named = true,
  },
  [sym_compound] = {
    .visible = true,
    .named = true,
  },
  [sym_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_group] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_atom] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_operator_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_operator_expression_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_compound_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_sequence_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quoted_atom_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_functor] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_operator] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_argument = 1,
  field_element = 2,
  field_functor = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_argument] = "argument",
  [field_element] = "element",
  [field_functor] = "functor",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [2] = {.index = 0, .length = 1},
  [3] = {.index = 1, .length = 2},
  [4] = {.index = 3, .length = 2},
  [5] = {.index = 5, .length = 2},
  [6] = {.index = 5, .length = 2},
  [7] = {.index = 7, .length = 1},
  [8] = {.index = 8, .length = 3},
  [9] = {.index = 11, .length = 2},
  [10] = {.index = 8, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_element, 1},
  [1] =
    {field_element, 1},
    {field_element, 2, .inherited = true},
  [3] =
    {field_element, 0, .inherited = true},
    {field_element, 1, .inherited = true},
  [5] =
    {field_argument, 2},
    {field_functor, 0},
  [7] =
    {field_argument, 1},
  [8] =
    {field_argument, 2},
    {field_argument, 3, .inherited = true},
    {field_functor, 0},
  [11] =
    {field_argument, 0, .inherited = true},
    {field_argument, 1, .inherited = true},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = alias_sym_operator,
  },
  [5] = {
    [0] = alias_sym_functor,
  },
  [8] = {
    [0] = alias_sym_functor,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
};

static const TSCharacterRange sym_symbol_character_set_1[] = {
  {'&', '&'}, {'*', '+'}, {'-', '/'}, {':', ':'}, {'<', '>'}, {'@', '@'}, {'\\', '\\'}, {'^', '^'},
  {'~', '~'},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(25);
      ADVANCE_MAP(
        '\'', 50,
        '(', 27,
        ')', 29,
        ',', 28,
        '-', 39,
        '/', 36,
        ';', 26,
        '[', 30,
        ']', 31,
        '#', 35,
        '$', 35,
        '?', 35,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(20);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      if (('&' <= lookahead && lookahead <= '@') ||
          ('\\' <= lookahead && lookahead <= '^') ||
          lookahead == '~') ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 1:
      if (lookahead == ' ') ADVANCE(45);
      if (lookahead == '\'') ADVANCE(51);
      if (lookahead == '/') ADVANCE(48);
      if (lookahead == '\\') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(5);
      if (lookahead > ' ' &&
          lookahead != 0x7f &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(49);
      END_STATE();
    case 2:
      if (lookahead == '*') ADVANCE(4);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(3);
      if (lookahead == '/') ADVANCE(53);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(4);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(3);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '/') ADVANCE(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      END_STATE();
    case 6:
      if (lookahead == 'U') ADVANCE(17);
      if (lookahead == 'u') ADVANCE(13);
      if (lookahead == '\'' ||
          lookahead == '\\' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't') ADVANCE(52);
      END_STATE();
    case 7:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      END_STATE();
    case 8:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 9:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      END_STATE();
    case 10:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(52);
      END_STATE();
    case 11:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(10);
      END_STATE();
    case 12:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(11);
      END_STATE();
    case 13:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(12);
      END_STATE();
    case 14:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(13);
      END_STATE();
    case 15:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(14);
      END_STATE();
    case 16:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(15);
      END_STATE();
    case 17:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(16);
      END_STATE();
    case 18:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 19:
      if (eof) ADVANCE(25);
      ADVANCE_MAP(
        '\'', 44,
        '(', 27,
        ')', 29,
        ',', 28,
        '-', 39,
        '/', 36,
        ';', 26,
        '[', 30,
        ']', 31,
        '#', 35,
        '$', 35,
        '?', 35,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(20);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      if (('&' <= lookahead && lookahead <= '@') ||
          ('\\' <= lookahead && lookahead <= '^') ||
          lookahead == '~') ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 20:
      if (eof) ADVANCE(25);
      ADVANCE_MAP(
        '\'', 44,
        '(', 32,
        ')', 29,
        ',', 28,
        '-', 39,
        '/', 36,
        ';', 26,
        '[', 30,
        ']', 31,
        '#', 35,
        '$', 35,
        '?', 35,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(20);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      if (('&' <= lookahead && lookahead <= '@') ||
          ('\\' <= lookahead && lookahead <= '^') ||
          lookahead == '~') ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 21:
      if (eof) ADVANCE(25);
      ADVANCE_MAP(
        '\'', 44,
        '(', 32,
        '-', 39,
        '/', 36,
        '[', 30,
        ']', 31,
        '#', 35,
        '$', 35,
        '?', 35,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(21);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      if (lookahead == '&' ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('.' <= lookahead && lookahead <= ':') ||
          ('<' <= lookahead && lookahead <= '@') ||
          ('\\' <= lookahead && lookahead <= '^') ||
          lookahead == '~') ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 22:
      if (eof) ADVANCE(25);
      ADVANCE_MAP(
        '(', 27,
        ')', 29,
        ',', 28,
        '/', 36,
        ';', 26,
        ']', 31,
        '#', 35,
        '$', 35,
        '?', 35,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(23);
      if (lookahead == '&' ||
          ('*' <= lookahead && lookahead <= '.') ||
          (':' <= lookahead && lookahead <= '@') ||
          ('\\' <= lookahead && lookahead <= '^') ||
          lookahead == '~') ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 23:
      if (eof) ADVANCE(25);
      if (lookahead == ')') ADVANCE(29);
      if (lookahead == ',') ADVANCE(28);
      if (lookahead == '/') ADVANCE(36);
      if (lookahead == ';') ADVANCE(26);
      if (lookahead == ']') ADVANCE(31);
      if (lookahead == '#' ||
          lookahead == '$' ||
          lookahead == '?') ADVANCE(35);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(23);
      if (lookahead == '&' ||
          ('*' <= lookahead && lookahead <= '.') ||
          (':' <= lookahead && lookahead <= '@') ||
          ('\\' <= lookahead && lookahead <= '^') ||
          lookahead == '~') ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 24:
      if (eof) ADVANCE(25);
      if (lookahead == ')') ADVANCE(29);
      if (lookahead == ',') ADVANCE(28);
      if (lookahead == '/') ADVANCE(2);
      if (lookahead == ';') ADVANCE(26);
      if (lookahead == ']') ADVANCE(31);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_LPAREN2);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_atom);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == '_') ADVANCE(18);
      if (lookahead == '#' ||
          lookahead == '$' ||
          lookahead == '?') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_atom);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == '*') ADVANCE(38);
      if (set_contains(sym_symbol_character_set_1, 9, lookahead)) ADVANCE(40);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == '*') ADVANCE(37);
      if (lookahead == '/') ADVANCE(40);
      if (set_contains(sym_symbol_character_set_1, 9, lookahead)) ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(4);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == '*') ADVANCE(37);
      if (set_contains(sym_symbol_character_set_1, 9, lookahead)) ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(4);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_symbol);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      if (set_contains(sym_symbol_character_set_1, 9, lookahead)) ADVANCE(40);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_symbol);
      if (set_contains(sym_symbol_character_set_1, 9, lookahead)) ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(8);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_quoted_atom_token1);
      if (lookahead == ' ') ADVANCE(45);
      if (lookahead == '/') ADVANCE(48);
      if (lookahead > ' ' &&
          lookahead != '\'' &&
          lookahead != '\\' &&
          lookahead != 0x7f &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(49);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_quoted_atom_token1);
      if (lookahead == '*') ADVANCE(46);
      if (lookahead == '/') ADVANCE(49);
      if (lookahead > 0x1f &&
          lookahead != '\'' &&
          lookahead != '\\' &&
          lookahead != 0x7f &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(47);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_quoted_atom_token1);
      if (lookahead == '*') ADVANCE(46);
      if (lookahead > 0x1f &&
          lookahead != '\'' &&
          lookahead != '\\' &&
          lookahead != 0x7f &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_quoted_atom_token1);
      if (lookahead == '*') ADVANCE(47);
      if (lookahead > 0x1f &&
          lookahead != '\'' &&
          lookahead != '\\' &&
          lookahead != 0x7f &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(49);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_quoted_atom_token1);
      if (lookahead > 0x1f &&
          lookahead != '\'' &&
          lookahead != '\\' &&
          lookahead != 0x7f &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_SQUOTE2);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_SQUOTE2);
      if (lookahead == '\'') ADVANCE(52);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 21},
  [2] = {.lex_state = 21},
  [3] = {.lex_state = 21},
  [4] = {.lex_state = 21},
  [5] = {.lex_state = 21},
  [6] = {.lex_state = 21},
  [7] = {.lex_state = 21},
  [8] = {.lex_state = 21},
  [9] = {.lex_state = 21},
  [10] = {.lex_state = 21},
  [11] = {.lex_state = 21},
  [12] = {.lex_state = 21},
  [13] = {.lex_state = 21},
  [14] = {.lex_state = 19},
  [15] = {.lex_state = 19},
  [16] = {.lex_state = 22},
  [17] = {.lex_state = 22},
  [18] = {.lex_state = 22},
  [19] = {.lex_state = 22},
  [20] = {.lex_state = 22},
  [21] = {.lex_state = 22},
  [22] = {.lex_state = 22},
  [23] = {.lex_state = 21},
  [24] = {.lex_state = 22},
  [25] = {.lex_state = 22},
  [26] = {.lex_state = 22},
  [27] = {.lex_state = 22},
  [28] = {.lex_state = 22},
  [29] = {.lex_state = 22},
  [30] = {.lex_state = 22},
  [31] = {.lex_state = 22},
  [32] = {.lex_state = 22},
  [33] = {.lex_state = 22},
  [34] = {.lex_state = 22},
  [35] = {.lex_state = 21},
  [36] = {.lex_state = 21},
  [37] = {.lex_state = 21},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 24},
  [42] = {.lex_state = 24},
  [43] = {.lex_state = 24},
  [44] = {.lex_state = 24},
  [45] = {.lex_state = 24},
  [46] = {.lex_state = 24},
  [47] = {.lex_state = 24},
  [48] = {.lex_state = 24},
  [49] = {.lex_state = 24},
  [50] = {.lex_state = 24},
  [51] = {.lex_state = 24},
  [52] = {.lex_state = 24},
  [53] = {.lex_state = 24},
  [54] = {.lex_state = 24},
  [55] = {.lex_state = 24},
  [56] = {.lex_state = 24},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LPAREN2] = ACTIONS(1),
    [sym_atom] = ACTIONS(1),
    [sym_symbol] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE2] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(55),
    [sym__expression] = STATE(44),
    [sym_operator_expression] = STATE(44),
    [sym__prefix_operator] = STATE(11),
    [sym__primary] = STATE(16),
    [sym__symbol_operand] = STATE(16),
    [sym_compound] = STATE(16),
    [sym_sequence] = STATE(16),
    [sym_group] = STATE(16),
    [sym_quoted_atom] = STATE(22),
    [aux_sym_operator_expression_repeat1] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_LBRACK] = ACTIONS(7),
    [anon_sym_LPAREN2] = ACTIONS(9),
    [sym_atom] = ACTIONS(11),
    [sym_symbol] = ACTIONS(13),
    [sym_number] = ACTIONS(15),
    [anon_sym_SQUOTE] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(2)] = {
    [sym__expression] = STATE(46),
    [sym_operator_expression] = STATE(46),
    [sym__prefix_operator] = STATE(11),
    [sym__primary] = STATE(16),
    [sym__symbol_operand] = STATE(16),
    [sym_compound] = STATE(16),
    [sym_sequence] = STATE(16),
    [sym_group] = STATE(16),
    [sym_quoted_atom] = STATE(22),
    [aux_sym_operator_expression_repeat1] = STATE(11),
    [anon_sym_LBRACK] = ACTIONS(7),
    [anon_sym_RBRACK] = ACTIONS(19),
    [anon_sym_LPAREN2] = ACTIONS(9),
    [sym_atom] = ACTIONS(11),
    [sym_symbol] = ACTIONS(13),
    [sym_number] = ACTIONS(15),
    [anon_sym_SQUOTE] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(3)] = {
    [sym__expression] = STATE(52),
    [sym_operator_expression] = STATE(52),
    [sym__prefix_operator] = STATE(11),
    [sym__primary] = STATE(16),
    [sym__symbol_operand] = STATE(16),
    [sym_compound] = STATE(16),
    [sym_sequence] = STATE(16),
    [sym_group] = STATE(16),
    [sym_quoted_atom] = STATE(22),
    [aux_sym_operator_expression_repeat1] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(21),
    [anon_sym_LBRACK] = ACTIONS(7),
    [anon_sym_LPAREN2] = ACTIONS(9),
    [sym_atom] = ACTIONS(11),
    [sym_symbol] = ACTIONS(13),
    [sym_number] = ACTIONS(15),
    [anon_sym_SQUOTE] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(4)] = {
    [sym__expression] = STATE(52),
    [sym_operator_expression] = STATE(52),
    [sym__prefix_operator] = STATE(11),
    [sym__primary] = STATE(16),
    [sym__symbol_operand] = STATE(16),
    [sym_compound] = STATE(16),
    [sym_sequence] = STATE(16),
    [sym_group] = STATE(16),
    [sym_quoted_atom] = STATE(22),
    [aux_sym_operator_expression_repeat1] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(7),
    [anon_sym_LPAREN2] = ACTIONS(9),
    [sym_atom] = ACTIONS(11),
    [sym_symbol] = ACTIONS(13),
    [sym_number] = ACTIONS(15),
    [anon_sym_SQUOTE] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(5)] = {
    [sym__expression] = STATE(52),
    [sym_operator_expression] = STATE(52),
    [sym__prefix_operator] = STATE(11),
    [sym__primary] = STATE(16),
    [sym__symbol_operand] = STATE(16),
    [sym_compound] = STATE(16),
    [sym_sequence] = STATE(16),
    [sym_group] = STATE(16),
    [sym_quoted_atom] = STATE(22),
    [aux_sym_operator_expression_repeat1] = STATE(11),
    [anon_sym_LBRACK] = ACTIONS(7),
    [anon_sym_LPAREN2] = ACTIONS(9),
    [sym_atom] = ACTIONS(11),
    [sym_symbol] = ACTIONS(13),
    [sym_number] = ACTIONS(15),
    [anon_sym_SQUOTE] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(6)] = {
    [sym__expression] = STATE(45),
    [sym_operator_expression] = STATE(45),
    [sym__prefix_operator] = STATE(11),
    [sym__primary] = STATE(16),
    [sym__symbol_operand] = STATE(16),
    [sym_compound] = STATE(16),
    [sym_sequence] = STATE(16),
    [sym_group] = STATE(16),
    [sym_quoted_atom] = STATE(22),
    [aux_sym_operator_expression_repeat1] = STATE(11),
    [anon_sym_LBRACK] = ACTIONS(7),
    [anon_sym_LPAREN2] = ACTIONS(9),
    [sym_atom] = ACTIONS(11),
    [sym_symbol] = ACTIONS(13),
    [sym_number] = ACTIONS(15),
    [anon_sym_SQUOTE] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(7)] = {
    [sym__expression] = STATE(56),
    [sym_operator_expression] = STATE(56),
    [sym__prefix_operator] = STATE(11),
    [sym__primary] = STATE(16),
    [sym__symbol_operand] = STATE(16),
    [sym_compound] = STATE(16),
    [sym_sequence] = STATE(16),
    [sym_group] = STATE(16),
    [sym_quoted_atom] = STATE(22),
    [aux_sym_operator_expression_repeat1] = STATE(11),
    [anon_sym_LBRACK] = ACTIONS(7),
    [anon_sym_LPAREN2] = ACTIONS(9),
    [sym_atom] = ACTIONS(11),
    [sym_symbol] = ACTIONS(13),
    [sym_number] = ACTIONS(15),
    [anon_sym_SQUOTE] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(8)] = {
    [sym__expression] = STATE(41),
    [sym_operator_expression] = STATE(41),
    [sym__prefix_operator] = STATE(11),
    [sym__primary] = STATE(16),
    [sym__symbol_operand] = STATE(16),
    [sym_compound] = STATE(16),
    [sym_sequence] = STATE(16),
    [sym_group] = STATE(16),
    [sym_quoted_atom] = STATE(22),
    [aux_sym_operator_expression_repeat1] = STATE(11),
    [anon_sym_LBRACK] = ACTIONS(7),
    [anon_sym_LPAREN2] = ACTIONS(9),
    [sym_atom] = ACTIONS(11),
    [sym_symbol] = ACTIONS(13),
    [sym_number] = ACTIONS(15),
    [anon_sym_SQUOTE] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(9)] = {
    [sym__expression] = STATE(53),
    [sym_operator_expression] = STATE(53),
    [sym__prefix_operator] = STATE(11),
    [sym__primary] = STATE(16),
    [sym__symbol_operand] = STATE(16),
    [sym_compound] = STATE(16),
    [sym_sequence] = STATE(16),
    [sym_group] = STATE(16),
    [sym_quoted_atom] = STATE(22),
    [aux_sym_operator_expression_repeat1] = STATE(11),
    [anon_sym_LBRACK] = ACTIONS(7),
    [anon_sym_LPAREN2] = ACTIONS(9),
    [sym_atom] = ACTIONS(11),
    [sym_symbol] = ACTIONS(13),
    [sym_number] = ACTIONS(15),
    [anon_sym_SQUOTE] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(10)] = {
    [sym__expression] = STATE(54),
    [sym_operator_expression] = STATE(54),
    [sym__prefix_operator] = STATE(11),
    [sym__primary] = STATE(16),
    [sym__symbol_operand] = STATE(16),
    [sym_compound] = STATE(16),
    [sym_sequence] = STATE(16),
    [sym_group] = STATE(16),
    [sym_quoted_atom] = STATE(22),
    [aux_sym_operator_expression_repeat1] = STATE(11),
    [anon_sym_LBRACK] = ACTIONS(7),
    [anon_sym_LPAREN2] = ACTIONS(9),
    [sym_atom] = ACTIONS(11),
    [sym_symbol] = ACTIONS(13),
    [sym_number] = ACTIONS(15),
    [anon_sym_SQUOTE] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      anon_sym_LPAREN2,
    ACTIONS(11), 1,
      sym_atom,
    ACTIONS(13), 1,
      sym_symbol,
    ACTIONS(17), 1,
      anon_sym_SQUOTE,
    ACTIONS(25), 1,
      sym_number,
    STATE(22), 1,
      sym_quoted_atom,
    STATE(23), 2,
      sym__prefix_operator,
      aux_sym_operator_expression_repeat1,
    STATE(18), 5,
      sym__primary,
      sym__symbol_operand,
      sym_compound,
      sym_sequence,
      sym_group,
  [36] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      anon_sym_LPAREN2,
    ACTIONS(11), 1,
      sym_atom,
    ACTIONS(13), 1,
      sym_symbol,
    ACTIONS(17), 1,
      anon_sym_SQUOTE,
    ACTIONS(27), 1,
      sym_number,
    STATE(22), 1,
      sym_quoted_atom,
    STATE(13), 2,
      sym__prefix_operator,
      aux_sym_operator_expression_repeat1,
    STATE(27), 5,
      sym__primary,
      sym__symbol_operand,
      sym_compound,
      sym_sequence,
      sym_group,
  [72] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      anon_sym_LPAREN2,
    ACTIONS(11), 1,
      sym_atom,
    ACTIONS(13), 1,
      sym_symbol,
    ACTIONS(17), 1,
      anon_sym_SQUOTE,
    ACTIONS(29), 1,
      sym_number,
    STATE(22), 1,
      sym_quoted_atom,
    STATE(23), 2,
      sym__prefix_operator,
      aux_sym_operator_expression_repeat1,
    STATE(32), 5,
      sym__primary,
      sym__symbol_operand,
      sym_compound,
      sym_sequence,
      sym_group,
  [108] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(37), 1,
      anon_sym_LPAREN2,
    ACTIONS(39), 1,
      sym_atom,
    ACTIONS(42), 1,
      sym_symbol,
    ACTIONS(35), 3,
      anon_sym_LBRACK,
      sym_number,
      anon_sym_SQUOTE,
    ACTIONS(31), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [136] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(37), 1,
      anon_sym_LPAREN2,
    ACTIONS(47), 1,
      sym_atom,
    ACTIONS(50), 1,
      sym_symbol,
    ACTIONS(35), 3,
      anon_sym_LBRACK,
      sym_number,
      anon_sym_SQUOTE,
    ACTIONS(45), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [164] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 1,
      sym_atom,
    ACTIONS(57), 1,
      sym_symbol,
    STATE(12), 1,
      sym__infix_operator,
    STATE(17), 1,
      aux_sym_operator_expression_repeat2,
    ACTIONS(53), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [187] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 1,
      sym_atom,
    ACTIONS(57), 1,
      sym_symbol,
    STATE(12), 1,
      sym__infix_operator,
    STATE(19), 1,
      aux_sym_operator_expression_repeat2,
    ACTIONS(59), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [210] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 1,
      sym_atom,
    ACTIONS(57), 1,
      sym_symbol,
    STATE(12), 1,
      sym__infix_operator,
    STATE(20), 1,
      aux_sym_operator_expression_repeat2,
    ACTIONS(59), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [233] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 1,
      sym_atom,
    ACTIONS(66), 1,
      sym_symbol,
    STATE(12), 1,
      sym__infix_operator,
    STATE(19), 1,
      aux_sym_operator_expression_repeat2,
    ACTIONS(61), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [256] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 1,
      sym_atom,
    ACTIONS(57), 1,
      sym_symbol,
    STATE(12), 1,
      sym__infix_operator,
    STATE(19), 1,
      aux_sym_operator_expression_repeat2,
    ACTIONS(69), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [279] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 1,
      sym_symbol,
    ACTIONS(71), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      sym_atom,
  [295] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 1,
      anon_sym_LPAREN,
    ACTIONS(77), 1,
      sym_symbol,
    ACTIONS(31), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      sym_atom,
  [313] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(81), 1,
      sym_atom,
    ACTIONS(84), 1,
      sym_symbol,
    STATE(23), 2,
      sym__prefix_operator,
      aux_sym_operator_expression_repeat1,
    ACTIONS(79), 4,
      anon_sym_LBRACK,
      anon_sym_LPAREN2,
      sym_number,
      anon_sym_SQUOTE,
  [333] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 1,
      sym_symbol,
    ACTIONS(87), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      sym_atom,
  [349] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      sym_symbol,
    ACTIONS(91), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      sym_atom,
  [364] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 1,
      sym_symbol,
    ACTIONS(95), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      sym_atom,
  [379] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 1,
      sym_symbol,
    ACTIONS(61), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      sym_atom,
  [394] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 1,
      sym_symbol,
    ACTIONS(101), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      sym_atom,
  [409] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 1,
      sym_symbol,
    ACTIONS(105), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      sym_atom,
  [424] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 1,
      sym_symbol,
    ACTIONS(109), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      sym_atom,
  [439] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      sym_symbol,
    ACTIONS(113), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      sym_atom,
  [454] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 1,
      sym_symbol,
    ACTIONS(117), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      sym_atom,
  [469] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 1,
      sym_symbol,
    ACTIONS(121), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      sym_atom,
  [484] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 1,
      sym_symbol,
    ACTIONS(125), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      sym_atom,
  [499] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 1,
      sym_symbol,
    ACTIONS(129), 5,
      anon_sym_LBRACK,
      anon_sym_LPAREN2,
      sym_atom,
      sym_number,
      anon_sym_SQUOTE,
  [513] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 1,
      sym_symbol,
    ACTIONS(133), 5,
      anon_sym_LBRACK,
      anon_sym_LPAREN2,
      sym_atom,
      sym_number,
      anon_sym_SQUOTE,
  [527] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(37), 1,
      sym_symbol,
    ACTIONS(35), 5,
      anon_sym_LBRACK,
      anon_sym_LPAREN2,
      sym_atom,
      sym_number,
      anon_sym_SQUOTE,
  [541] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      anon_sym_SQUOTE2,
    STATE(40), 1,
      aux_sym_quoted_atom_repeat1,
    ACTIONS(137), 2,
      aux_sym_quoted_atom_token1,
      sym_escape_sequence,
  [555] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(144), 1,
      anon_sym_SQUOTE2,
    STATE(39), 1,
      aux_sym_quoted_atom_repeat1,
    ACTIONS(141), 2,
      aux_sym_quoted_atom_token1,
      sym_escape_sequence,
  [569] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 1,
      anon_sym_SQUOTE2,
    STATE(39), 1,
      aux_sym_quoted_atom_repeat1,
    ACTIONS(146), 2,
      aux_sym_quoted_atom_token1,
      sym_escape_sequence,
  [583] = 4,
    ACTIONS(150), 1,
      anon_sym_COMMA,
    ACTIONS(152), 1,
      anon_sym_RPAREN,
    ACTIONS(154), 1,
      sym_comment,
    STATE(48), 1,
      aux_sym_compound_repeat1,
  [596] = 4,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(154), 1,
      sym_comment,
    ACTIONS(156), 1,
      anon_sym_SEMI,
    STATE(47), 1,
      aux_sym_source_file_repeat1,
  [609] = 4,
    ACTIONS(154), 1,
      sym_comment,
    ACTIONS(158), 1,
      anon_sym_COMMA,
    ACTIONS(161), 1,
      anon_sym_RBRACK,
    STATE(43), 1,
      aux_sym_sequence_repeat1,
  [622] = 4,
    ACTIONS(154), 1,
      sym_comment,
    ACTIONS(163), 1,
      ts_builtin_sym_end,
    ACTIONS(165), 1,
      anon_sym_SEMI,
    STATE(42), 1,
      aux_sym_source_file_repeat1,
  [635] = 4,
    ACTIONS(150), 1,
      anon_sym_COMMA,
    ACTIONS(154), 1,
      sym_comment,
    ACTIONS(167), 1,
      anon_sym_RPAREN,
    STATE(49), 1,
      aux_sym_compound_repeat1,
  [648] = 4,
    ACTIONS(154), 1,
      sym_comment,
    ACTIONS(169), 1,
      anon_sym_COMMA,
    ACTIONS(171), 1,
      anon_sym_RBRACK,
    STATE(51), 1,
      aux_sym_sequence_repeat1,
  [661] = 4,
    ACTIONS(154), 1,
      sym_comment,
    ACTIONS(173), 1,
      ts_builtin_sym_end,
    ACTIONS(175), 1,
      anon_sym_SEMI,
    STATE(47), 1,
      aux_sym_source_file_repeat1,
  [674] = 4,
    ACTIONS(150), 1,
      anon_sym_COMMA,
    ACTIONS(154), 1,
      sym_comment,
    ACTIONS(178), 1,
      anon_sym_RPAREN,
    STATE(50), 1,
      aux_sym_compound_repeat1,
  [687] = 4,
    ACTIONS(150), 1,
      anon_sym_COMMA,
    ACTIONS(154), 1,
      sym_comment,
    ACTIONS(180), 1,
      anon_sym_RPAREN,
    STATE(50), 1,
      aux_sym_compound_repeat1,
  [700] = 4,
    ACTIONS(154), 1,
      sym_comment,
    ACTIONS(182), 1,
      anon_sym_COMMA,
    ACTIONS(185), 1,
      anon_sym_RPAREN,
    STATE(50), 1,
      aux_sym_compound_repeat1,
  [713] = 4,
    ACTIONS(154), 1,
      sym_comment,
    ACTIONS(169), 1,
      anon_sym_COMMA,
    ACTIONS(187), 1,
      anon_sym_RBRACK,
    STATE(43), 1,
      aux_sym_sequence_repeat1,
  [726] = 2,
    ACTIONS(154), 1,
      sym_comment,
    ACTIONS(173), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
  [734] = 2,
    ACTIONS(154), 1,
      sym_comment,
    ACTIONS(189), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [742] = 2,
    ACTIONS(154), 1,
      sym_comment,
    ACTIONS(191), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [750] = 2,
    ACTIONS(154), 1,
      sym_comment,
    ACTIONS(193), 1,
      ts_builtin_sym_end,
  [757] = 2,
    ACTIONS(154), 1,
      sym_comment,
    ACTIONS(195), 1,
      anon_sym_RPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(11)] = 0,
  [SMALL_STATE(12)] = 36,
  [SMALL_STATE(13)] = 72,
  [SMALL_STATE(14)] = 108,
  [SMALL_STATE(15)] = 136,
  [SMALL_STATE(16)] = 164,
  [SMALL_STATE(17)] = 187,
  [SMALL_STATE(18)] = 210,
  [SMALL_STATE(19)] = 233,
  [SMALL_STATE(20)] = 256,
  [SMALL_STATE(21)] = 279,
  [SMALL_STATE(22)] = 295,
  [SMALL_STATE(23)] = 313,
  [SMALL_STATE(24)] = 333,
  [SMALL_STATE(25)] = 349,
  [SMALL_STATE(26)] = 364,
  [SMALL_STATE(27)] = 379,
  [SMALL_STATE(28)] = 394,
  [SMALL_STATE(29)] = 409,
  [SMALL_STATE(30)] = 424,
  [SMALL_STATE(31)] = 439,
  [SMALL_STATE(32)] = 454,
  [SMALL_STATE(33)] = 469,
  [SMALL_STATE(34)] = 484,
  [SMALL_STATE(35)] = 499,
  [SMALL_STATE(36)] = 513,
  [SMALL_STATE(37)] = 527,
  [SMALL_STATE(38)] = 541,
  [SMALL_STATE(39)] = 555,
  [SMALL_STATE(40)] = 569,
  [SMALL_STATE(41)] = 583,
  [SMALL_STATE(42)] = 596,
  [SMALL_STATE(43)] = 609,
  [SMALL_STATE(44)] = 622,
  [SMALL_STATE(45)] = 635,
  [SMALL_STATE(46)] = 648,
  [SMALL_STATE(47)] = 661,
  [SMALL_STATE(48)] = 674,
  [SMALL_STATE(49)] = 687,
  [SMALL_STATE(50)] = 700,
  [SMALL_STATE(51)] = 713,
  [SMALL_STATE(52)] = 726,
  [SMALL_STATE(53)] = 734,
  [SMALL_STATE(54)] = 742,
  [SMALL_STATE(55)] = 750,
  [SMALL_STATE(56)] = 757,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__primary, 1, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__prefix_operator, 1, 0, 1),
  [37] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__prefix_operator, 1, 0, 1),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym__prefix_operator, 1, 0, 1), REDUCE(sym__primary, 1, 0, 0),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym__prefix_operator, 1, 0, 1), REDUCE(sym__primary, 1, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__symbol_operand, 1, -1, 0),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym__prefix_operator, 1, 0, 1), REDUCE(sym__symbol_operand, 1, -1, 0),
  [50] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym__prefix_operator, 1, 0, 1), REDUCE(sym__symbol_operand, 1, -1, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operator_expression, 2, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_operator_expression_repeat2, 2, 0, 0),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_operator_expression_repeat2, 2, 0, 0), SHIFT_REPEAT(36),
  [66] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_operator_expression_repeat2, 2, 0, 0), SHIFT_REPEAT(35),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operator_expression, 3, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_atom, 2, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_atom, 2, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__primary, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_operator_expression_repeat1, 2, 0, 0),
  [81] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_operator_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [84] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_operator_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_atom, 3, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_atom, 3, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compound, 5, 0, 10),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_compound, 5, 0, 10),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sequence, 2, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sequence, 2, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_operator_expression_repeat2, 2, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group, 3, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_group, 3, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sequence, 4, 0, 3),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sequence, 4, 0, 3),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sequence, 3, 0, 2),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sequence, 3, 0, 2),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compound, 4, 0, 5),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_compound, 4, 0, 5),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_operator_expression_repeat2, 3, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_operator_expression_repeat2, 3, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compound, 4, 0, 6),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_compound, 4, 0, 6),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compound, 5, 0, 8),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_compound, 5, 0, 8),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__infix_operator, 1, 2, 1),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__infix_operator, 1, 2, 1),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__infix_operator, 1, 1, 1),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__infix_operator, 1, 1, 1),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [139] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [141] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quoted_atom_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quoted_atom_repeat1, 2, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [148] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [158] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sequence_repeat1, 2, 0, 4), SHIFT_REPEAT(9),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sequence_repeat1, 2, 0, 4),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [175] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [182] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_compound_repeat1, 2, 0, 9), SHIFT_REPEAT(10),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_compound_repeat1, 2, 0, 9),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sequence_repeat1, 2, 0, 2),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_compound_repeat1, 2, 0, 7),
  [193] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_ilk_meta(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "ilk_meta",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
